### ISSUE TITLE
Question about representative fish

### ISSUE THREAD

**Issue by HarrietVanOverzee** [ices-tools-dev/RDBES#10]
Following the presentation Kirstin gave this morning I have another question regarding when length measurements have been conducted on haul level and age sampling on trip level. It was indicated that in order to include this information you need to add an extra row in the FO table (where FOaggregationLevel’=’T’). I was wondering what then should be filled in for FOseqNum. Should you then just sequentially add another number (after the haul numbers)?
Thank you in advance.

**Comment by davidcurrie2001** [comment]
I've been using the number 0 - its clear its not a real haul number.

**Comment by davidcurrie2001** [comment]
@HarrietVanOverzee Does using FOsequenceNumber = 0 for trip level aggregations work for you?

**Comment by HarrietVanOverzee** [comment]
@davidcurrie2001 Yes, thank you
