### ISSUE TITLE
CLofficialWeight range: allow for at least 1 decimal?

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#100]
Some very rare species may not be reported at present resolution (kg)

**Comment by josefineegekvist** [comment]
Agree that one decimal can be allowed in the CLofficialWeight. Then CLscientificWeight should also be changed to allow for one decimal. Need to be changed in the data format and in the database.

**Comment by josefineegekvist** [comment]
Discussed 11/01/2022 by RDBES CE CL subgroup
It seem to be agreed at core group meeting 10/3/2021 to change the field to allow for one decimal.

**Comment by HenrikK-N** [comment]
The data type for CLofficialWeight and CLscientificWeight was changed from Integer to Decimal(1) (with 1 decimal) in the data model. This will first take effect after the RDBES system update late August 2023. Same as #169.
