### ISSUE TITLE
add DEsampled to DE table?

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#101]
I noticed that "DEsampled" does not exist in DE - could it be useful to report a missing strata? take missing strata in covid times....

**Comment by lizclarke** [comment]
Yes, we think there should be a DEsampled field, and an associated DEreasonNotSampled. But would the lack of sampling cause issues in upload as would only have a DE and SD table? (Note spelling mistake in RS_ReasonForNotSampling - not available.)

**Comment by lizclarke** [comment]
The DEsampled and DEreasonNotSampled fields are now included in the data model.

**Comment by Ruth-R-Kelly** [comment]
I see this issue is now closed, but I was wondering under present circumstance if it would be useful/interesting to add 'COVID19' to the ReasonForNotSampling vocab options? I can use the code 'Other' but it does seem like a lot of people could have this reason.

**Comment by davidcurrie2001** [comment]
@Ruth-R-Kelly can you send the request for this new code to rdbsupport@ices.dk and it will then be picked up for discussion.  It sounds like a good idea to me.
