### ISSUE TITLE
Sampling landings (ie alternative logbooks filled in by fishermen)

### ISSUE THREAD

**Issue by luciazarauz** [ices-tools-dev/RDBES#105]
This is something that has been discussed several times, but I am not sure about the final conclusion. 

Some of us have alternative sources of information which are used to estimate the landings of some fleets. Sometimes it is a sample of the total fleet. Other times it is a census and all vessels of the fleet are reporting their trips. An example of this could be alternative logbooks which are filled in by the SSF. 

Could this information be reported in the RDBES format? , using table SA? would the variable total weight be used to report the sampled total weight (ie the weight reported in the alternative logbooks)?

Thanks!

**Comment by HenrikK-N** [comment]
The support for estimated landings are in the landing and effort tables CL and CE and it is documented there, but additional support for the sample will at this point not be made in the sample table SA.
