### ISSUE TITLE
potential overlap between mitigation device and selection device

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#106]
I am struggling with the conceptual differences between selection devices and bycatch mitigation devices. I think definitions need to be improved to make the distinction clear, and that some codes in the two codes lists need to be differentiated more clearly. If they do turn out to be overlapping, we should consider merging them to one list.

In particular, I'd like to have clarified two questions:

Are 'Sealexcl' and 'Turtexcl' in RS_incidentialByCatchMitigateD not kinds of 'Selection panel' in RS_SelectionDevice?
Is 'Sortgrid' in RS_incidentialByCatchMitigateD any different from 'Grid' in RS_SelectionDevice?
In general, how is exlusion of incidental bycatch different from traditional selection?

referring to the code lists:
RS_incidentialByCatchMitigateD: https://vocab.ices.dk/?ref=1613
RS_SelectionDevice described in: https://github.com/ices-tools-dev/RDBES/issues/102 and closely corresponding to IC_SelectivityDevice: https://vocab.ices.dk/?ref=339

Amongst other places, both codes are used in the FO-table.

(A secondary concern is whether we need both RS_SelectionDevice and IC_SelectivityDevice.)

**Comment by nmprista** [comment]
Issue already solved by by-catch subgroup and following core-group plenaries. Reopen if not.
