### ISSUE TITLE
rename BVfishId to BVnationalFishId and update its description

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#110]
This variable secures the link between RDBES data and the many detailed information available on the at national level that is of interest to a multiplicity of EGs (WGSMARTDOTS, WGBIOP, WGSAM, benchmarks, ...). 

Renaming it will clarify its purpose and help it being correctly uploaded.

The description should also be simplified to 

Unique Individual National numerical ID of the fish. Used to link RDBES data to other information available at national level and other ICES systems like SmartDots.

**Comment by edvinf** [comment]
This sounds like a good idea. I just want to make sure we specify clearly what the uniqueness-constraint is. For instance: "Individual National numerical ID of the fish. Unique within sample", if uniqueness within sample is what is intended.

**Comment by davidcurrie2001** [comment]
Sounds fine to me.  Just to highlight we have also received the following information about Smart Dots: "_Each time an event is set up, a folder for that event is created. Everything related to that event goes into that folder. Therefore it is not possible to use images from SmartDots in two different events. The images will need to be uploaded again for the new event, and then one can use whatever fishID one wants._"
So it really is the responsibility of national institutes to always upload the same fish with the same id if we want to be able to link the data in different systems together.

**Comment by HenrikK-N** [comment]
It is a good suggestion. Yes we should update the field 'BVfishId' to suggestion 'BVnationalUniqueFishId'? We have to agee on the description, suggestion:
"Individual National numerical ID of the fish. Unique across all species, years etc."? If possible to have a unique fish id across all species, years etc.? Not just unique within sample.

**Comment by nmprista** [comment]
Some further analysis on this issue - seems to me that one alternative worth considering is to instead have instituteFishID as a biological variable under " RS_BiologicalMeasurementType". This would make it non-mandatory and allow for strings to be used (which may be useful when data providers do not have access to their internal database IDs).

**Comment by KirstenBirchHaakansson** [comment]
@davidcurrie2001 @HenrikK-N - are you handling this issues in the code subgroup?

**Comment by HenrikK-N** [comment]
@KirstenBirchHaakansson: Yes
@nmprista: Good alternative suggestion, but for now we will concentrate on the 'BVfishId' to suggestion 'BVnationalUniqueFishId'.

**Comment by HenrikK-N** [comment]
It was agreed to update to 'BVnationalUniqueFishId', and change to string if SmartDot is using strings for fishid.

**Comment by HenrikK-N** [comment]
This have been implemented.
