### ISSUE TITLE
What to do when the information for any of the mandatory fields for a sample is not available

### ISSUE THREAD

**Issue by IsaBruno1** [ices-tools-dev/RDBES#111]
We have included 2 variants of samples in hierarchy 7 (:
    1. On-shore sampling from vendors (mixed trips): We haven't trip information
    2. Sampling boxes from size categories (from buyers):  We usually know the source trip (not always).

In both cases, there is a stratification by length, because we select the length classes we  need to sample, in order to obtain a good representation of the full length range. 

We can have samples of type "1" and "2" for the same species.

This file with a list of all the mandatory fields in the LE. I have included some comments for each field (in green when information is available and in red when we don't know it)
[RDBES_LE_H7.xlsx](https://github.com/ices-tools-dev/RDBES/files/6236212/RDBES_LE_H7.xlsx)

What can we do when the information for any of the mandatory fields for a sample is not available...? (Vessel, Area, Métier, Gear, ...)

Some clarifications:

The boxes of fish that we buy from vendors are usually made up of specimens caught by different boats and come from several ICES Divisions close to each other.

 In case On-shore sampling from vendors (mixed trips), We have information on stock and catch date, but we don't know the boat or the ICES Division. In case Sampling boxes from size categories (from buyers), we usually know the boat, sometimes the ICES Division.

We always know the stock. But, depending on the species and stocks, we can have different posibilities:
1. On-shore sampling from vendors (mixed trips): unknown boat(s), unknown métier
1.1.- We know the ICES Division, but we don't know the boat (the samples may come from 2 or 3 different boats, fishing in the same area)
1.2.- We don't know the boat or the ICES Division 
2. Sampling boxes from size categories (from buyers) (only 1 trip):
2.1.- We know the boat and the ICES Division
2.2.- We know the boat, but We don't know the ICES Division (the ship works in a fishing zone that includes several ICES Divisions). In these cases, it would be difficult and incorrect to determine a dominant ICES Division, but we could identify the fishing subarea.
2.3.- We don't know the boat or the ICES Division. As in the previous case, We could identify the ICES Subárea.

**Comment by HenrikK-N** [comment]
Answers:
1.1 and 1.2 It is suggested to use the field 'LEmixedTrip' = yes, 
2.2 and 2.3 It is suggested to use the best possible estimate of a dominante ICES division from Landing Event ('LEmixedTrip' = yes) and Fishing Operation (FOaggregationLevel (is over all hauls/aggregationlevel) = Trip) in the Sample table.
In general when the division is not known, use the best estimate of the dominant ICES division.
When the boat is not known use the 'LEmixedTrip' = yes.

**Comment by IsaBruno1** [comment]
Comments:
We were already using 'LEmixedTrip' = yes, as you suggest, in the case of an unknown ship.
Unfortunately, in the case of the Spanish fleet operating in ICES Subarea 7, it is not always possible to estimate a dominant ICES division. We need that, in these cases, it is accepted that the required level is ICES Subarea ... Otherwise, a good part of the biological information that we have (almost all that related to demersal species) will not be able to be implemented.

**Comment by HenrikK-N** [comment]
It is possible to use subareas, so it should be possible to upload the data. Hopefully if the subarea covers several stocks for a species, it is possible for that species to determine at least one area within the stock's areas for each stock.

**Comment by IsaBruno1** [comment]
Thanks, Henrik. Of course, we will use the ICES Division level whenever possible.

**Comment by rix133** [comment]
So, on the same topic what to put to the mandatory field **LEencryptedVesselCode** if we don't know the boat   (ie question 1)
does  setting 'LEmixedTrip' = "Y" make this field non-mandatory or should I create an imaginary boat for each onshore event? What other fields become non-mandatory if the 'LEmixedTrip' = "Y" unfortunately searching for word "mixed" from the documentation gives only FAQ11  that given no further info.

**Comment by davidcurrie2001** [comment]
@rix133 can you open a new issue for your specific question - thanks.
