### ISSUE TITLE
Origin of the dates used to calculate month, quarter, and year fields in CE, CL

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBES#116]
There was a discussion at WKRDB-POP3 about whether the actual date of the fishing effort / catch shoudl be used to generate the month/quarter/year fields in CE and CL, or if peopel shoudl just use the landing date of the trip.  At the workshop we said to use the landing date for the month/quarter/year of both CE, and CL.  The following comment was receievd at the end of the workshop with respect to this:
"Fishing effort. *It was agreed to calculate an effort by “vessel x trip x Unique Key where the year, quarter and month are set according to the landing date”.  I respect the common opinion. However, we may lose information (or be misinformed) on migration of stocks which could be essential for stock estimation. I understand that it is difficult to find one way of data reporting convenient both for biologists and economists however, providing of ALL BIOLOGICALLY IMPORTANT information should be the priority.  If it is impossible to make it in one table, the separate tables could be designed to make both biologists and economists happy.*"

**Comment by HenrikK-N** [comment]
The priority is still to keep a direct relation between the CE and CL. We will look into the uploaded data.

**Comment by HenrikK-N** [comment]
After further disucssions it has been decided to determine; year, quarter and month by the landing date, both to keep the consistency between landing and effort data, but also in acknowledgement of the fact that not all countries can provide the catch date for catches.
