### ISSUE TITLE
"Examples of Hierarchies 1-8 A-D.xlsx” spreadsheet referred to in documentation but is not available

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBES#118]
The "Examples of Hierarchies 1-8 A-D.xlsx” spreadsheet is referred to in the RDBES documentation but is not currently available.  We either need to stop referring to it, or create an updated version of this spreadsheet.

**Comment by nmprista** [comment]
A user also raised this issue to me by email last week. 
I suggest we delete reference to that annex and we use the data uploaded in september to create that example after the data call. 

That will be better that an attempt to quick fix the original file (that is now 4 versions old) and the best option to secure the examples are complete and match the specs of the data model (varnames, code-lists, M/O fields, etc).

**Comment by davidcurrie2001** [comment]
I've removed the reference to this spreadsheet from the documentation.  Good plane about using data upload in September to create an up-to-date version of this spreadsheet.
