### ISSUE TITLE
FAQ to documentation: decreasing weights/numbers when sampling without replacement [SRSWOR]

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#119]
In WKRDB-POP3 the following question was raised:

We took n = 2 samples of w = 5kg using SRSWOR from a total catch of N=10 and W = 50kg. Because we used SRSWOR, our 1st sample was taken from N=50 and W = 50kg and our 2nd sample was taken from N= 10-9 =  9 and W = 50-5 = 45 kg. How should this be declared in the RDBES? Should the number and kgs we report in the totals change with each sample ... OR should we report the totals as N = 10 and W = 50 kg?

Answer given to users at the time was the following:

- _NumTotal is defined as the number of units in the stratum/cluster, staying the same for all samples in SRSWOR - so it makes sense to define weightTotal consistently/similarly_
- _The probability of inclusion [SAinclusionProb] of each row under SRSWOR is 2/10 [there are N=10 units of 5kg -> 50/5=10]. This is the value that enters HT estimators._
- _With regards to probability of selection  [SAselectionProb]: it is 1/10 for the first unit, 1/9 for the second unit, and so on. The prob of selection is not what we will use in HT design-based estimation of the SRSWOR, but for other purposes it can be calculated via the sequence number present in the SA (and all other tables). That number is defined as "The sequence number identify the selections made with in each strata and cluster combination. Preferably **representing the order of the selections.**"_
- _When one mentions sampling 10/50, then 10/50, one is approximating the probability of inclusion using the weight_
- _When one mentions sampling 5/50 then 5/45, and so on, you are approximating the probability of selection using the weight_
- _Note that the reduction in variance that stems from the increase in sampling fraction with each iteration is captured by the finite-population correction used in the SRSWOR variance formula._

It was considered that it should be put as FAQ as the question is likely experienced by many users

**Comment by HenrikK-N** [comment]
It is suggested to make it a FAQ.

**Comment by nmprista** [comment]
added to documentation (presently FAQ 21)
