### ISSUE TITLE
Code type errors in Documentation CE table

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBES#120]
The following codes are not updated in the CE documentation table
**RS_DataTypeForScientificWE** should likely be  RS_DataTypeOfScientificWE
 **RS_DataSourceForScientificWE**  should  likely be  RS_DataSourceOfScientificWE
 **RS_incidentialByCatchMitigationDevice** should likely be  BycatchMitigateDevice
 **LOCODE_Harbour** should likely be Harbour_LOCODE #

**Comment by HenrikK-N** [comment]
We are working on this.

**Comment by HenrikK-N** [comment]
The corrections of typos have been made.
