### ISSUE TITLE
QC-scripts: Test data files added

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBES#123]
I have added 2 test data files for CE and CL.  You might like to edit your QC scripts so that they read in these files by default - that way if somebody wants to download the scripts they can see how they work without already needing CE and CL in the correct format.

**Comment by HenrikK-N** [comment]
Waiting for feedback from the QC script group

**Comment by karolinamg** [comment]
RDBES NationalOverviews QC script has been updated and tested with test data.

**Comment by josefineegekvist** [comment]
Thanks. I think that the script is ready for use now. I have tested with Danish data.

**Comment by HenrikK-N** [comment]
Feedback have been received.
