### ISSUE TITLE
Documentation: Fishing Operation (FO) table column order is unambiguous

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBES#125]
So the Table **Fishing Operation** in the file **RDBES Data Model.xlsx** has a column **Order** definded from 1:50 but inbetween the numbers there are 5 fields that have a value **NEW** . What should be is the actual order in the RDBES upload files?

**Comment by HenrikK-N** [comment]
That will be fixed

**Comment by HenrikK-N** [comment]
It has been fixed.
