### ISSUE TITLE
OSsequenceNumber & LEsequenceNumber

### ISSUE THREAD

**Issue by luciazarauz** [ices-tools-dev/RDBES#126]
We need confirmation about the level of aggregation of OSsequenceNumber & LEsequenceNumber

In our data we have:
* One SDid per fleet, 
* OS table is stratified by quarter. That is, OSstratumName is defined by fleet + quarter. 
* OSid is made from the combination of fleet+quarter+marketday.
* LE is not stratified.

Then, each OSsequenceNumber has to be unique for each SDid (fleet), or for each OSstratumName (fleet + quarter)?

And LEsequenceNumber, has to be unique for each OSid? or also SDid?

Thank you!

**Comment by HenrikK-N** [comment]
In the OnshoreEvent OS table there are two different combinations of fields that have to be unique for each SamplingDetail (SDid) parent (see the 3rd column C in the data model header Unique combination of fields UK1 and UK2): 

The Unique key UK1: SDId, OSlocode, OSLocationName, OSsamplingDate, OSsamplingTime

The Unique key UK2: SDId, OSsequenceNumber

Then, each OSsequenceNumber has to be unique for each SDid (fleet), or for each OSstratumName (fleet + quarter)?

Answer: The OSsequenceNumber has to be unique for each SDid (fleet).

And then LEsequenceNumber will be unique for each OSid? 

Answer: It will not automatically be unique for each OSid, you have to upload a unique LEsequenceNumber for each record under one specific OnshoreEvent (OSid).
