### ISSUE TITLE
Documentation issue: CLofficialWeight and CLscientificWeight 

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBES#127]
The CLofficialWeight and CLscientificWeight  specify in Basic checks that it should be  0-2 000 000 000 (i.e. 2 million t), The RDBES system does not accept 0 into the fields of CLofficialWeight and CLscientificWeight 
I guess the Basic checks  should state 1-2 000 000 000 (i.e. 2 million t) if near 0 landings are not expected to be reported.

**Comment by HenrikK-N** [comment]
We will update the check to accept 0 for the fields of CLofficialWeight and CLscientificWeight.

**Comment by HenrikK-N** [comment]
The update have been implemented, 0 is now accepted for the fields of CLofficialWeight and CLscientificWeight.
