### ISSUE TITLE
FTnumberOfHaulsOrSets range

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [ices-tools-dev/RDBES#128]
FTnumberOfHaulsOrSets is mandatory and from 1-300, when FTsampler == "Observer” and FTsamplingType == “at-sea”. 

This cause some troubles, since we sometimes have sampled trips with no valid hauls or none at all, due to bad weather / gear, so it would be nice if it was possible to declare 0 in FTnumberOfHaulsOrSets

**Comment by HenrikK-N** [comment]
The minimum value for FTnumberOfHaulsOrSets is now 0.
