### ISSUE TITLE
RDBES Data Model CL CE.xlsx  - Qualitative bias

### ISSUE THREAD

**Issue by Kasia-MIR** [ices-tools-dev/RDBES#13]
Hi, 
I have a question about requirement of qualitative bias. In CL this field is optional but in CE is mandatory. Is there any difference between them? Or should it also be optional in CE?

**Comment by HenrikK-N** [comment]
Rename 'CEqualitativeBias' to include which field it refers to, like for CL. Look into making CL mandatory like for CE. 2020 06 10 webex.

**Comment by HenrikK-N** [comment]
We will make the CEqualitativeBias optional.
