### ISSUE TITLE
CL and CE, Fishing technique

### ISSUE THREAD

**Issue by josefineegekvist** [ices-tools-dev/RDBES#135]
Suggestion by WGCATCH for a better field description: ‘Fishing technique used by Annual Economic Reporting for fleet segmentation, and requested in the EU FDI data call’.

**Comment by josefineegekvist** [comment]
Discussed 11/01/2022 by RDBES CE CL subgroup
Ok to change the field description in the CE CL format.

**Comment by HenrikK-N** [comment]
The Core Group agreed.
