### ISSUE TITLE
Statistical rectangles do not always uniquely identify a Nephrops Functional Unit

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBES#14]
In the RDBES we did not include a spatial field for Nephrop Functional Unit because we thought that if the statistical rectangle was mandatory for Nephrops then we would always be able to uniquely identify the relevant FU.  However the functional units that are used in Nephrops assessments are not the spatial units defined by statistical rectangles but are informed by the actual properties of the sea-bed.  This means some statistical rectangles do not map to a unique FU e.g. 30E1 is in both FU19 and FU2021

**Comment by HenrikK-N** [comment]
Since this is not needed for the data call, this will be taken up in November. This might also be needed by sandeel.

**Comment by KirstenBirchHaakansson** [comment]
According to http://www.ices.dk/sites/pub/Publication%20Reports/Expert%20Group%20Report/Fisheries%20Resources%20Steering%20Group/2019/WGCSE/17_Section15_Nephrops_fu14_2019.pdf the stock are defined per rectangle - or is it a new definition?

Presently SAndeel areas are defined by rectangle - at least in the North Sea

**Comment by davidcurrie2001** [comment]
According to a Nephrops guy at our institute "..._the assessment FUs are not defined by stat rectangles, but by grounds which sometimes make funny shapes due to rocky/sandy/muddy patches._"

**Comment by KirstenBirchHaakansson** [comment]
@davidcurrie2001 
Could you check with your Nephrops guys, since that contradicts the definitions in the WGCSE report

**Comment by davidcurrie2001** [comment]
This all came from an issue raised by someone who attends the assessment.  The issue seems to be specifically for FU19 and FU2021.

**Comment by HenrikK-N** [comment]
To my knowledge the nephrops stocks are defind by FU, which are made up/defined by statistical rectangles, that is how it is set up in InterCatch for the assessment. The statistical rectangles I believe are selected based on properties of the sea bed/buttom.

**Comment by davidcurrie2001** [comment]
But you're not seeing what people are doing to raise their data for InterCatch.   Statistical rectangles are imaginary lines and Nephrops have limited respect for them.

**Comment by maristeguie** [comment]
_Nephrops_ sampling and UWTV surveys are split by FU. Therefore, some of the samples of FU19 and some of the samples of FU2021 they both come from rectangle 30E1. Because these two FUs share the rectangle 30E1.

However, it's true that _Nephrops_ landings are split by Statistical rectangle. This means that all landings from ICES rectangle 30E1 specifically are assigned to FU2021.

**Comment by KirstenBirchHaakansson** [comment]
Good point - thanks

This is not the case for the sandeel stoks in the North Sea - rectangle is use for comercial landings and samples

**Comment by davidcurrie2001** [comment]
![image003](https://user-images.githubusercontent.com/40271317/202188229-ee901f98-5f3e-4c64-ae6b-a75f62160f1e.jpg)

Image comparing selected FUs and stat rectangles.

**Comment by davidcurrie2001** [comment]
FUs can now be recorded in the XXfisheriesManagementUnit columns using values from ICES "AreaNonFAO" code list https://vocab.ices.dk/?codetypeguid=d94d4dca-c8d1-40ea-8b82-ff93ae3a7dcf
The issue is now resolved :-)
