### ISSUE TITLE
Is NotSampled a selection method?

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [ices-tools-dev/RDBES#142]
Code:	NotSampled
Description:	Used in cases where the selected unit is not sampled

I'm not sure why we have included this code. In my head NotSampled is a realisation of a selection and not a method for selection.Further,  we already have plenty of fields for added info about sampling or not e.g. FOsampled and FOreasonNotSampled

If the reason is inclusion of exclusions, then I think we need a more telling code for that.

**Comment by nmprista** [comment]
NotSampled is used for unsampled strata (see example 2 of documentation). 

However, like @KirstenBirchHaakansson says, the definition in vocab (https://vocab.ices.dk/?ref=1637: "used in cases when the selected unit is not sampled") results not clear now that other variables have been added. 

One way forward could be to delete "notSampled" and append the following italics to the definition of code "notApplicable", adjusting the documentation accordingly.

notApplicable ->"Used in cases where a selection does not take place _(e.g., when a stratum is not sampled)_"

**Comment by KirstenBirchHaakansson** [comment]
I like Nuno's suggestion, so can we do that and close the issue?

**Comment by lizclarke** [comment]
Estimation subgroup discussed on 16/03/2022 and agreed to update the definition of the code in the vocab and example 2 in the documentation. To be confirmed by the core group.

**Comment by HenrikK-N** [comment]
The core group agreed to the deletion of 'NotSampled' and the update of the 'NotApplicable' description.

**Comment by nmprista** [comment]
Following up on that decision I noticed the following adjustments still need to be made:
- "OutOfFrame" needs to be deleted from code list "selectionMethod" (https://vocab.ices.dk/?ref=1637)
- "OutOfFrame" needs to be added to code list "reasonForNotSampling" (https://vocab.ices.dk/?ref=2). I suggest the following definition "not included in sampling frame"
- update of doc file

**Comment by nmprista** [comment]
Doc file is now updated
Description of code "NotApplicable" has been updated

Remains to do:
Code "NotSampled" still in code list [//vocab.ices.dk/?ref=1637](https://vocab.ices.dk/?ref=1637). Should be deleted.
Code "OutOfFrame" still in code list [//vocab.ices.dk/?ref=1637](https://vocab.ices.dk/?ref=1637). Should be deleted.
Code "OutOfFrame" not in code list[//vocab.ices.dk/?ref=1641](https://vocab.ices.dk/?ref=1641). Should be added with description "not included in sampling frame"

**Comment by HenrikK-N** [comment]
The code updates have been implemented.
