### ISSUE TITLE
CE data format: official/scientific variables for additional fields?

### ISSUE THREAD

**Issue by josefineegekvist** [ices-tools-dev/RDBES#148]
In the CE data format, it is possible to specify both official and scientific effort for most variables, but not for:
GT Days at sea
GT Fishing days
GT Fishing hours
Gear dimensions
Number of FADs/buoys
Number of supporting vessels.

Should we add the extra fields with possibility of both official and scientfic or should we specify that they should be reported as scientific?

**Comment by HenrikK-N** [comment]
If in doubt it should always be specified in the description of the field, that it is the scientific data which should be used. ‘The scientific’ have been added to the description of the following fields: CEgTDaysAtSea, CEgTFishingDays, CEgTFishingHours, CEgearDimensions, CEnumberOfFAD and CEnumberofSupVes.
