### ISSUE TITLE
CEexclusiveEconomicZone field name in CL table data model?

### ISSUE THREAD

**Issue by jcraigMS** [ices-tools-dev/RDBES#156]
In the data model CL CE.xlxs, within the tab that defines the CL table, there is a field name:  CEexclusiveEconomicZone, with R Name: CEeconZone
Is this a mistake and should I correct the field name to CLexclusiveEconomicZone ?

**Comment by HenrikK-N** [comment]
Yes, it is a mistake, it should be CLexclusiveEconomicZone. It is a minor typo, so it will be updated with the next update soon.
