### ISSUE TITLE
Fishing area category clarification

### ISSUE THREAD

**Issue by jcraigMS** [ices-tools-dev/RDBES#157]
Hi,
It would be good to have some additional guidance on the definition of  MO=Marine water (open sea)  and MC=Marine water (coast).
The official logbook landings are resolved to rectangle. In 2021 all our TRS or SAL are from rectangles crossing the coast so I have defined these as MC. But is there a specific definition that can be applied?
Thank you

**Comment by HenrikK-N** [comment]
Hi
So far the specification is that from the coast and to about 4 nautic miles from the coast is it MC=Marine water (coast). For further clarification please ask the chair from WGBAST Martin Kesler.
