### ISSUE TITLE
CLlandingLocation for RegDis has not been documented

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBES#160]
So I have trouble finding the place in the documentation that specifies what should be the **Harbour_LOCODE** be if the CLcatchCategory is RegDis. Could this be specified in the CL table in the documentation? 

e.g. CElandingCategory provide the code None for this purpose.

 As I understand the field CLlandingLocation  is mandatory and **Harbour_LOCODE** is taken from an external list  that ICES does not maintain itself.

Actually the same question applies to  CLlandingCountry with **ISO_3166**. I think the code to use there should be **ZZ** but its not in the code lists [ISO-3166-2](https://en.wikipedia.org/wiki/ISO_3166-2). But its in [ISO-3166-1](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)

**Comment by HenrikK-N** [comment]
In the case of RegDis the same Harbour_LOCODE, where the vessel did the landing, should be used. (The text will be added to CLlandingLocation)
It is the same answer regarding CLlandingCountry, again use the country in which the landing took place.  The follwing text will be added to CLlandingCountry: "In the case of RegDis the same country, where the vessel did the landing, should be used."
