### ISSUE TITLE
Upload Error: VesselLengthClass code invalid for RDBES

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBES#161]
While trying to upload to RDBES I get the following error:

'CEvesselLengthCategory' | VL1218 | Enumeration | The 'CEvesselLengthCategory' element is invalid
-- | -- | -- | --

However the documentation states clearly that the code should be 
 [VesselLengthClass](https://vocab.ices.dk/?ref=1725)  that has the code  **VL1218** (not deprecated)

What am I missing?

**Comment by davidcurrie2001** [comment]
Even though a code isn't deprecated it still might not be valid for use in the RDBES - unfortunately I don't think there is currently a way to identify this in the public view of the ICES vocabulary.  Only non-overlapping vessel length codes are allowed in the RDBES to avoid ambiguity - I believe these are: 'VL0006','VL0608','VL0810','VL1012','VL1215','VL1518','VL1824','VL2440','VL40XX'.
Hopefully in the future the ICES vocab server will show whether or not a code is valid for a specific database.

**Comment by HenrikK-N** [comment]
The ICES Data Centre is working on showing only the specific codes related to the different systems, which uses the Vocab. Until that is ready, it is possible to see which codes that can be used for the RDBES, by searching codes through the RDBES.
That is done by doing the following:
In Vocab search for ‘RDBES’ select the ICES Codes (22) or Codes (22) tab and click RDBES.
Now scroll to the relevant code type and click it, then the page refreshes, then scroll to the bottom of the page where only the relevant accepted codes are shown.
