### ISSUE TITLE
SAreasonNotSampled(SA) needed

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#168]
In SA users can presently specify why FM or BV were not sampled. This info summarizes what is sampled and not in lower hierarchy. However, information on the reason for not having sampled the SAid itself is not being provided. 

This differs from remaining tables and is necessary for situations when multiples samples are taken and some may not have been analyzed (e.g., for species composition).

**Comment by HenrikK-N** [comment]
We will discuss it at the Core Group.

**Comment by HenrikK-N** [comment]
It was agreed to add a new field:  SAreasonNotSampled to the SA table.

**Comment by HenrikK-N** [comment]
The field have been added to the latest version of the CS data model.
