### ISSUE TITLE
Decimals in CLofficialWeight and CLscientificWeight

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#169]
The official weight information SLU processes for RDBES and assessment purposes has a resolution of 0.1kg in both logbooks and sales. The present resolution of these two fields in RDBES/CL is 1 kg which leads to totals we report not matching the official totals. At least 1 decimal is required in those fields for accurate reporting and correct distinction between very low catches and true absences.

**Comment by HenrikK-N** [comment]
We will discuss it at the Core Group.

**Comment by HenrikK-N** [comment]
Hi Nuno. The CG discussed this and would like you to give an example where it is a problem, to give it some context? Cheers

**Comment by HenrikK-N** [comment]
At the Core group meetign from Nuno: In Sweden they use decimal in CLofficialWeight and CLscientificWeight. Both in the landing declarations and the logbooks.
In Denmark Salesnotes have decimals but logbooks does not have.
Ireland does not record less than a kilogram. 
It was agreed to change the CLofficialWeight and CLscientificWeight from integer to decimal number with 1 decimal.

**Comment by KirstenBirchHaakansson** [comment]
In the description for CLscientificWeight change 'The estimated scientific weight.' to 'The estimated scientific live weight in kg'

**Comment by HenrikK-N** [comment]
The description have been updated

**Comment by HenrikK-N** [comment]
The data type for CLofficialWeight and CLscientificWeight was changed from Integer to Decimal(1) (with 1 decimal) in the data model. This will first take effect after the RDBES system update late August 2023.
