### ISSUE TITLE
CE download format problem

### ISSUE THREAD

**Issue by karolinamg** [ices-tools-dev/RDBES#170]
The downloaded CE file seem to have extra quote marks which results in multiple rows being written into the last column (CEencryptedVesselIds) and total row count approximately half than the original file.

**Comment by HenrikK-N** [comment]
Hi Karolina
Please send and email to RDBsupport@ices.dk regarding this issue.
Cheers Henrik

**Comment by HenrikK-N** [comment]
It is not closed.
