### ISSUE TITLE
Inclusion of Base port in the CL and CE tables

### ISSUE THREAD

**Issue by luciazarauz** [ices-tools-dev/RDBES#174]
Dear coregroup,

We have found that we would need the inclusion of the variable Base Port, to reproduce the estimations we are doing. 

The reason behind is that in Spain, AZTI is doing the following sampling: 

- port sampling: we sample the landings sold in Basque Ports. And the proxi we use for this is to use the landings landed in Basque Ports plus the landings landed by Basque Vessels abroad (which are usually sold in the Basque Cuntry).

- onbopard sampling: we sample just Basque vessels (they are the ones we have access to)

We discussed this in yesterday's meeting. I am sorry we didn't raised it before. We just didn't realize...

If you need any further infromation, please, do not hesitate in asking

Best regards

Lucía

**Comment by HenrikK-N** [comment]
Hi Lucia
Can you let us know what you suggest the field could be called, and what the description for the field could be?
Br Henrik

**Comment by HenrikK-N** [comment]
Dear Lucia

Thanks for the information and good alternatives to have the information in existing fields; metier6, nationalFishingActivity or samplingScheme.

Br Henrik
