### ISSUE TITLE
Fishing Area Category (CE) CEfishingAreaCategory

### ISSUE THREAD

**Issue by Kasia-MIR** [ices-tools-dev/RDBES#175]
I have question about the field CEfishingAreaCategory.
Field definition: 'Fishing area category is needed for salmon and sea trout. Codes e.g.: MO=Marine water (open sea), MC=Marine water (coast), FW= fresh water'.
Should I take an effort of targeting species of a trip? Example: A trip targeting herring with sea trout bycatch, the fishing activity category should be given for such trip or not?

**Comment by HenrikK-N** [comment]
The Fishing area category will normally for the effort be MO=Marine water (open sea), I guess in your example with a trip targeting herring, but with a bycatch of sea trout. But for effort spend in coastal area (about 4 nautical miles from the coast) typically targeting sea trout or salmon the code MC=Marine water (coast) should be used.
