### ISSUE TITLE
Update xsd files

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBES#176]
Hi @HenrikK-N   - please can you update the xsd files in https://github.com/ices-tools-dev/RDBES/tree/master/XSD-files 
I use these in my validation functions when creating the RDBES exchange files.

**Comment by HenrikK-N** [comment]
Hi Dave
I have now updated the XSD files on this GitHub under Code and XSD-Files.
Cheers

**Comment by davidcurrie2001** [comment]
Great - thanks for the quick response.
