### ISSUE TITLE
RDBES CL upload - incorrect duplicate check - need to add CLdeepSeaRegulation 

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBES#177]
The RDBES CL upload is incorrectly flagging rows as duplicates when they have different values for the CLdeepSeaRegulation column.  According to the RDBES CL data model this column should be part of the unique key.

Two vessels can be fishing in the same area, targeting the same species, using the same gear/metier but they might not both fall within the Deep-Sea Regulation because: "..., _a fishing vessel carrying out a fishing activity shall be deemed to target deep-sea species if its communications about catches (in the logbook, landing declarations, sales notes or similar document) in a calendar year concerned contain at least 8 % of deep-sea species in any fishing trip._" https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2016.354.01.0001.01.ENG

The upload portal is only reporting the following fields as the key fields:
CLdataTypeOfScientificWeight, CLdataSourceOfScientificWeight, CLsamplingScheme, CLdataSourceLandingsValue, CLlandingCountry, CLvesselFlagCountry, CLyear, CLquarter, CLmonth, CLarea, CLstatisticalRectangle, CLdataSourceOfStatisticalRectangle, CLfisheriesManagementUnit, CLgsaSubarea, CLjurisdictionArea, CLfishingAreaCategory, CLfreshWaterName, CLexclusiveEconomicZone, CLspeciesCode, CLspeciesFaoCode, CLlandingCategory, CLcatchCategory, CLregDisCategory, CLcommercialSizeCategoryScale, CLcommercialSizeCategory, CLnationalFishingActivity, CLmetier6, CLincidentalByCatchMitigationDevice, CLlandingLocation, CLvesselLengthCategory, CLfishingTechnique

**Comment by davidcurrie2001** [comment]
Email sent to RDBsupport@ices.dk

**Comment by HenrikK-N** [comment]
Remember for technical issues please sent email to RDBsupport@ices.dk, the RDBsupport issue is dealt with.
