### ISSUE TITLE
RDBES Submission Overview - show details in reverse chronological order

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBES#178]
In the RDBES Submission Overview page it would be great if the details of the failed/successful submissions were reported in reverse chronological order i.e. most recent first.  We are normally interested in the status of the most recent submissions so it would be clearer if they were at the top of the list.  (This is obviously not a major issue/problem)

**Comment by HenrikK-N** [comment]
It will be looked into when times allow.
