### ISSUE TITLE
OSlocode and OSsamplingDate when OutOfFrame

### ISSUE THREAD

**Issue by luciazarauz** [ices-tools-dev/RDBES#179]
Dear all,

We have an onshore sampling design with Hierarchy 5. 
In some of our sampling strata, there are ports which are not part of the sampling frame. 
We plan to report them in an "OutofFrame" strata in the OS table, in order to indicate how many onshore events are we losing, by not including those ports in our sampling frame.
However, we find problems to fill in the variables OSsamplingdate (as there were no sampling) and OSlocode (as our "outOfFrame" strata may comprise several ports)

what do you recommend us to do?

Thank you

best regards

**Comment by HenrikK-N** [comment]
It is suggested for this RDBES 2023 data call to use the last day of the year '20xx-12-31' for the OSsamplingDate and 'ES999' (Desc: 'Spain - Unknown'), and then OSreasonNotSampled to 'OutOfFrame'. The Core Group will look more into this and there may be a different approach in the future.

**Comment by luciazarauz** [comment]
ok. We will do like that. Thank you very much
