### ISSUE TITLE
H8 XML schema does not follow documentation

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBES#180]
I think the documentation suggest that the FT table is optinal but the XSD suggests that there is at least one FT record:
https://github.com/ices-tools-dev/RDBES/blob/ec10f4a821a686381081232eee7cac4917f99ced/XSD-files/H8.xsd#L60

Is the schema or the documentation misleading?

**Comment by HenrikK-N** [comment]
Hi Richard
This was a technical issue, which I dealt and solved the same day on RDBsupport@ices.dk. So I close it here.
