### ISSUE TITLE
FOexclusiveEconomicZoneIndicator - error while uploading data

### ISSUE THREAD

**Issue by mrska** [ices-tools-dev/RDBES#181]
In the FOexclusiveEconomicZoneIndicator  'EU' value displays as error while loading. 

It looks like a wrong vocab is connected with this column. In the Data Model there is a link to the exclusiveEconomicZone in vocab not the exclusiveEconomicZoneIndicator

**Comment by HenrikK-N** [comment]
You are right, the hyper link to codes in vocab for exclusiveEconomicZoneIndicator is to the exclusiveEconomicZone, that have now been internally updated and will be published next time there is a bigger update to the CS data model.
