### ISSUE TITLE
Question: how to fill SAsampleWeightMeasured and SAtotalWeightMeasured

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBES#182]
I'm a bit confused how to fill these fields from the documentation so I'll try to explain my reasoning with an example. Suppose I have a Species list of 3 species (COD, RED, YEL). I have one haul sampled for all the species  in the list (SSid=1) In the  SA table I have 2 species present (the third was not in the basket ).  

I understand that if the sample was taken after sorting the **totalWeight** should be the total weight of the catch of this species and the **sampleWeight**  should be the amount sampled of this species. See below:

SAid | SSid | SAspeciesCodeFAO | SAsampleWeightMeasured | SAtotalWeightMeasured | SAunitType | SAselectionMethod
-- | -- | -- | -- | -- | -- | --
 2 | 1 | RED | 17510 | 1081000 | Basket | SRSWOR
1 | 1 | COD | 109430 | 110000 | Basket | SRSWOR

Now if I the sample was taken before sorting the **totalWeight** should be the sum of total catch of all the species in the species list. and the **sampleWeight** should be the total weight of the sample (i.e. species pooled):

SAid | SSid | SAspeciesCodeFAO | SAsampleWeightMeasured | SAtotalWeightMeasured | SAunitType | SAselectionMethod
-- | -- | -- | -- | -- | -- | --
 1 | 1 | COD | 126940 | 1196000 | Basket | SRSWOR
2 | 1 | RED | 126940 | 1196000 | Basket | SRSWOR

is this reasoning correct? Or is there something else expected? If this is correct it is a bit confusing that simply looking at the SA table gives an impression that there was equal amount of RED and COD sampled if sampled pre-sorting. 

Also note that the **totalWeight** of first table does not equal the total weight of the second table (because there is 5 kg of something else (either not in the specieslist or in the species list but not in the sample) in the catch. Is this correct or the second example **totalWeight** should be sum of all species in the species list?

**Comment by HenrikK-N** [comment]
It is suggested to have a combined SA record with all species as a parent SA record with the totalweights, see the following. Followed by each known species and lastly the 5 kg of the unknown species.
![image](https://github.com/ices-tools-dev/RDBES/assets/40856502/786f931c-db4a-4d6d-8bf1-116a1efc1775)
The Animalia in the 1st line represent all species. In the 4th line we take it to represent the unknown species.

**Comment by rix133** [comment]
Thank you for your answer. However, in your example you answered for the situation where the 5 kg is in the sample but **OutOfFrame** I was rather interested in something else. My question was about a situation where there total catch is 1196000 g and the total sample is 126940 g (that is known to be COD and RED). i.e. **Is the second table correct if we actually know the totalWeights from the catch and sample but we obtain this info after sampling?**
