### ISSUE TITLE
DifferenceReason codes

### ISSUE THREAD

**Issue by josefineegekvist** [ices-tools-dev/RDBES#184]
Could we add the following codes to the DifferenceReason codes (http://vocab.ices.dk/?ref=1617)

'Metier' (Estimated metier). To differenciate when the metier is based on logbook information or estimated (which is the case of SSF in some cases)
'Areamis' (Area misreporting). Could this either be changed to 'Area correction' or added as a new code with 'Areacorr (Area correction)
'Other' (Other corrections)
'Multiple' (Multiple corrections). E.g., in case there is both an area correction and a scientific metier estimation

**Comment by HenrikK-N** [comment]
At this late point of the data call, I think we will take the discussions after the data call deadline, so all countries upload data from mainly the same set of stabile codes.

**Comment by HenrikK-N** [comment]
We agreed to:
Update: code 'Areamis' to 'Area' and the description from 'Area misreporting' to 'Area correction'. 
Update code 'Corrowb' to 'Overwbox'. 
Update code ‘NoDiff’ to ‘NoDiffAssumed’ and description to ‘No difference assumed’
Update description on ‘Unallocc’ ‘Unallocated catches’ to ‘Unallocated or additional weights that cannot be allocated to specific trips or vessels.’
The following codes should be added:
Code          Description
'Metier'      'Estimated metier, based on logbook information or estimated (which is the case of SSF in some cases)
'Other'      'Other corrections'
'Multiple'  ‘Multiple corrections, e.g., in case there is both an area correction and a scientific metier estimation’
‘Species’	‘Species correction’ 
‘NoDiffKnown’  ‘No difference known’
‘NoOfficial’ ‘No official data available’
