### ISSUE TITLE
CE Official Days at Sea

### ISSUE THREAD

**Issue by josefineegekvist** [ices-tools-dev/RDBES#186]
Currently, the Official Days at Sea in the CE table can't be uploaded with the values 0, '', NA or NotApplicaple.
In some cases, e.g., for the Small Scale Fisheries, there is no official days at sea, only scientific estimates, e.g., based on sales notes. Had to assign the value 0.01 to upload the data.

**Comment by rix133** [comment]
Yes, I had to do the same fix

**Comment by HenrikK-N** [comment]
It sounds like the minimum value of Official Days at Sea in the CE table needs to be set to 0. That will be done on agreement after the data call deadline.
