### ISSUE TITLE
FOarea and FOrectangle

### ISSUE THREAD

**Issue by luciazarauz** [ices-tools-dev/RDBES#188]
This is not a big issue, but it could be useful that the guidelines recommend whether to use the rectangle/area of the FOstart or FOend, in case they fall into different rectangles/areas

**Comment by HenrikK-N** [comment]
The Core Group will after the data call deadline agree and give guidelines whether to use the FOstart or FOend for rectangle/area when they are not the same. If in doubt now, a suggestion could be to use the rectangle/area where most of the fishing operation took place.

**Comment by luciazarauz** [comment]
ok, thanks

**Comment by HenrikK-N** [comment]
It has been agreed to add the following guideline use the stat. rect./area, where most fishing is done, if in doubt use the stat. rect/area where the fishing ends.

**Comment by HenrikK-N** [comment]
The text have been added to the FOarea and FOstatRect descriptions.
