### ISSUE TITLE
On Shore Event - Auxiliary Variable

### ISSUE THREAD

**Issue by karolinamg** [ices-tools-dev/RDBES#191]
I want to add the total weight landed from all trips during a specific on shore event for each species sampled at that on shore event, as an auxiliary variable (hierarchy 5).  I can do this by creating a new sequence number in the onshore event table for each species, however, in my understanding a new sequence number indicates a new selection of an onshore event, which is not true. Multiple landing events are selected within one selection of an onshore event. 

The other option is to use the OS sampling time, however, I don't understand the description:
"Start Sampling time. If there is more that one sampling event during a day this field must be filled."
Does the _more that one sampling event_ mean a different selection of the same on shore event at a different time the same day or a different selection of a landing event within the same on shore event?

**Comment by HenrikK-N** [comment]
It is suggested to try to use the species selection using SSstratumName for each species, and use the auxiliary fields for the total and sampled weight.
