### ISSUE TITLE
Vocabularies: CL & CE

### ISSUE THREAD

**Issue by Kasia-MIR** [ices-tools-dev/RDBES#193]
There are some inconsistencies between data model and ices vocab. 
The vocabularies of CLmesSizRan, CLsupReg, CLgeoInd, CLspeConTech, CLFDIconCod, CEmesSizRan, CEsupReg, CEgeoInd, CEspeConTech do not exist in the ices.vocab. 
I used [FDI_MESH_SIZE_RANGE], [FDI_SUPRA_REGION], [FDI_GEO_INDICATOR], [FDI_SPECON_TECH], [FDI_CONFIDENTIALITY].

**Comment by HenrikK-N** [comment]
Yes, those are the correct once to use, that will be updated.

**Comment by HenrikK-N** [comment]
The data model have been updated.
