### ISSUE TITLE
CLexplainDifference and correction for overweight in boxes

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [ices-tools-dev/RDBES#198]
During the submission the CLscientificWeight was not multiplied with the factor we use for correction for overweight in boxes

The main reasoning being that it becomes rather nontransparent what we have done, when a lot of the lines ends up with a combination of reasons for the difference between the CLofficialWeight and CLscientificWeight

Related to 
#184

**Comment by KirstenBirchHaakansson** [comment]
We have discussed if we should include the calculation of the correction factor in the estimation and thereby document what we do in TAF instead of just adding it to the CLscientificWeight

Pros:

1. We document what we do

Cons:

1. We are not able to include the needed information in the present CS data model (maybe with some heavy thinking we would be able)
2. scientific weight would differ between the CL and the output of estimation

**Comment by HenrikK-N** [comment]
It was briefly discussed but there was no conclusion.

**Comment by HenrikK-N** [comment]
The weight could be corrected for multiple reasons, which will not directly appear in the DifferentReason, but that level is not needed internationally. The codes in  DifferentReason can be used for explaining the potential difference with not further details.
