### ISSUE TITLE
SAsex == indetermined is missing

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#22]
From webex 2020 060 10

Currently there is an option for "unsexed" which means not sexed at all (no attempt was made, fish was already processed, etc) or that sex determination is carried out at a later stage; 

but an option for "indetermined" in the sense of "attempt made to determine but the exact sex could not be identified (e.g., it was very immature, the gonad was very dubius, sick, etc) is missing.

**Comment by nmprista** [comment]
Feedback obtained from lab:
- Male = ok. 
- Female = ok. 
- Transitional = what is this - need to define? 
- Not sampled / NA = no attempt made or necessary evidence not present (no gonads in fish, already processed, etc)
- Cannot determine = attempt made but sex cannot be determined (e.g., very young juveniles)

**Comment by davidcurrie2001** [comment]
I will combine this with the SCRDB 2019 meeting recommendation to talk to WGBIOP about the code lists for biological parameters.

**Comment by davidcurrie2001** [comment]
I have sent a mail to the WGBIOP chairs this morning and will follow up with them.

**Comment by davidcurrie2001** [comment]
Nuno and I spoke with Julie Davies (WGBIOP) and Jane Godiksen (WGSMART) today.  We agreed that the best course of action would be for the RDBES to use the [SEXCO reference list](http://vocab.ices.dk/?ref=45) for sex instead of RS_Sex.  
An entry for “T” might need to be added to this list, along with distinguishing the 2 different cases of Unsexed (not attempted, and attempted but not possible)

**Comment by HenrikK-N** [comment]
SEXCO: 
Code	Description	
F 	Female 	
H 	Hermaphrodite 	
I 	Immature 	
M 	Male 
U 	Undetermined 	
X 	Mixed 

RS_Sex: 
Code	Description	
F 	F 	
M 	M 	
T 	T 	
U 	U

**Comment by HenrikK-N** [comment]
T is use in the current RDB, with a total of 14176, with 2166 for year 2020. So 'T' should be added to the SEXCO.

**Comment by HenrikK-N** [comment]
Suggest updates: 
H Hermaphrodite and/or transitional
U Undetermined (no attempt made)
I Immature (attempt made but sex could not be destinguished)

**Comment by HenrikK-N** [comment]
The following was implemented:
Added code 'T' and desc: 'Transitional'
Updated desc. for code 'I' from 'Immature' to 'Immature - attempt made but sex could not be destinguished'
Updated desc. for code 'U' from 'Undetermined' to 'Undetermined - no attempt made'
Implemented the 9/6-21
