### ISSUE TITLE
Can't upload almost any species in SL: SLcommercialTaxon and SLspeciesCode errors

### ISSUE THREAD

**Issue by Eucrow** [ices-tools-dev/RDBES#23]
Trying to upload the SL table, the screening throws me a "The SLcommercialTaxon element is invalid" and "The 'SLspeciesCode' element is invalid" in all of the species we have to upload. I checked the species aphia ID codes and they are right.

Looking at ices sharepoint I found an SL example with the species 126417. So I tried to upload the SL file with this species and, surprisingly, the upload worked.

Is there any kind of filter which allow us or deny us to upload certain species?

**Comment by edvinf** [comment]
In order to help identifying errors, we are encouraging users that experience this kind of problems to provide an example of a valid aphia id that reproduce the problem. A valid aphia id is one that has status 'accepted'. The status of aphia ids can be checked by searching for the aphia id on http://www.marinespecies.org .

**Comment by Eucrow** [comment]
126437 (Melanogrammus aeglefinus) is an example. It is an accepted aphiaID but throws the errors previously commented.

**Comment by davidcurrie2001** [comment]
I have found a similar problem with 105872 which is an accepted code, and is in the code list https://vocab.ices.dk/?CodeID=202672 but causes a problem when trying to upload a file.  I have sent a demo file to the rdbsupport email address to demonstrate the issue.

**Comment by davidcurrie2001** [comment]
ICES re-synced the RDBES with the SpecWorms code list this morning and that has resolved my problem.  @Eucrow do you want to try uploading your data again and see if it works now?

**Comment by Eucrow** [comment]
Thanks @davidcurrie2001. This update of the SpecWorms in ICES has resolved our problem with those species :)

**Comment by davidcurrie2001** [comment]
@Eucrow Great - I'll close this issue - please let us know if you have any further problems with species codes.
