### ISSUE TITLE
DEsamplingSchemeType code list in documentation doesn't match with ICES vocabularies

### ISSUE THREAD

**Issue by Eucrow** [ices-tools-dev/RDBES#24]
The description of field DEsamplingSchemeType have an "DCF" option, which doesn't exists in RS_SamplingSchemeType table of ICES vocabularies.

**Comment by HenrikK-N** [comment]
The 'DCF' should not be in the code list, regional or national should be used. The 'DCF' will be removed from the data model. 4 new needed codes for incidential by catch will though be added.
