### ISSUE TITLE
FTsamplingType code list in documentation doesn't match with ICES vocabularies

### ISSUE THREAD

**Issue by Eucrow** [ices-tools-dev/RDBES#25]
In 'RDEBES Data Model.xlsx', the description fields referes to values "At-sea" and "On-shore". Those doesn't match with RS_SamplingType of ICES Referece Codes: "At-Sea" and "On-Shore", therefore an error is thrown in RDBES when a file is uploaded without the correct value.

**Comment by edvinf** [comment]
Thanks for reporting. The code descriptions in RDEBES Data Model.xlsx has now been corrected.
