### ISSUE TITLE
Error 500 when a not well formatted file is uploaded

### ISSUE THREAD

**Issue by Eucrow** [ices-tools-dev/RDBES#29]
By mistake, if try to upload a file with the first row with wrong format (for example, the first row contains the headers of the file), or with the wrong number of columns, the application returns an error 500 and the message "We will get back to you asap". An error message more accurate or friendly would be appreciate, like "The format is incorrect" (and avoid the 500 code error which is a little misleading).

![image](https://user-images.githubusercontent.com/10269446/85279822-5baefa00-b487-11ea-8128-de16f5997eaa.png)

**Comment by edvinf** [comment]
Thanks a lot for reporting. In order to check when the error is fixed it would be useful to have an example file, or some example lines that produce it. Could you provide that as a comment to this issue, or send to RDBsupport <RDBsupport@ices.dk>?

**Comment by Eucrow** [comment]
I forget to add that this error is thrown with the SL files, buy I didn't test with other ones.

Usually we get the file with the first row as colnames which I should delete before the upload:
```
SLRECORDTYPE,SLCOUNTRY,SLINSTITUTE,SLSPECIESLISTNAME,SLYEAR,SLCATCHFRACTION,SLCOMMERCIALTAXON,SLSPECIESCODE
SL,ES,353,IEO_M_SAP_DCF,2019,Lan,126421,126421
```

**Comment by HenrikK-N** [comment]
We are working on giving better error messages. If you still get the error please send an email to RDBsupport@ices.dk
