### ISSUE TITLE
Import and export tools

### ISSUE THREAD

**Issue by ldbk** [ices-tools-dev/RDBES#30]
Hi,

We are trying to develop the RDBES export from our national database. Our IT team asks for the possibility to use the tools developed by ICES to (1) do not start from scratch, (2) do not reinvent the wheel and (3) ensure the reproducibility of the quality checks used by ICES to validate the RDBES data. Do these tools are available somewhere? 

Thank you!

Laurent

**Comment by HenrikK-N** [comment]
Hi Laurent
Yes it is possible to get the source code for the RDBES. The most relevant would be the export code and the library for check against the XSD. This is the first request for this, so we will look into a way to do this.
Br Henrik

**Comment by ldbk** [comment]
Hi,

Any news regarding our request ?

Lauret

**Comment by davidcurrie2001** [comment]
Hi @ldbk Henrik is on leave at the moment so will need to follow up with this on his return.  

I have worked on some reasonably generic R functions to validate RDBES data using the ICES xsd files, and produce exchange files -take a look at https://github.com/davidcurrie2001/MI_RDBES_ExchangeFiles 
"RDBES_Functions.R" contains the functions, and "CreateExchangeFiles.R" shows how I use them

**Comment by HenrikK-N** [comment]
Hi Laurent
I am sorry it took so long. We have developed the RDBES in C# code, so to read or use the source code it is needed to be a C# developer. Unfortunately we do not have the resources to give support on the source code, of cause we can answer some questions, but it is expected that the users will read and work with the code themselves. The following zip files are attached: 
The CsvToXmlConverter.zip contains C# projects for importing the csv file and convert it into XML.
The DataValidationChecks.zip contains C# projects for validation of the data in XML format.
The XML2DB.zip contains C# projects for inserting the hierarchical XML data into the database. 
The Db2CSV.zip contains C# projects for exporting the data in the database into a csv file.
[CsvToXmlConverter.zip](https://github.com
[Db2Csv.zip](https://github.com/ices-tools-dev/RDBES/files/7863109/Db2Csv.zip)
/ices-tools-dev/RDBES/files/7863102/CsvToXmlConverter.zip)
[DataValidationChecks.zip](https://github.com/ices
[XML2DB.zip](https://github.com/ices-tools-dev/RDBES/files/7863108/XML2DB.zip)
-tools-dev/RDBES/files/7863105/DataValidationChecks.zip)

**Comment by ldbk** [comment]
Hi Henrik & Dave,
Thanks for the messages: @davidcurrie2001 yes I use your code since the beginning, @HenrikK-N thanks a lot for the sharing of the c# code, I think it will be really useful for our dev teams but unfortunately the links tower the archives are pointing to nothing. Can you fix that ?

**Comment by HenrikK-N** [comment]
Hi Laurent
I have created a subfolder under the RDBES called 'Source_code' there you can find the zip files, that should work.
Br Henrik
