### ISSUE TITLE
Avoid the use of "NA" as values in code lists

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBES#31]
Can we avoid using "NA" as a value in a code list - it makes life difficult when you're dealing with the data in R.

E.g. if we don't have an actual value for the GSA sub-area then according to the code list Areas_GFCM_GSA we are supposed to use "NA" - this is a bit of a pain in R since NA has a special meaning.

**Comment by edvinf** [comment]
I agree. It would be consistent with other code lists if we add the code "Unknown" to the code list for this field.

**Comment by davidcurrie2001** [comment]
I will look into the RS_ code lists, see which have values of "NA", and suggest alternatives.

**Comment by davidcurrie2001** [comment]
The following code lists have values with NA: 
RS_NationalFishingActivity: Change to NotApplicable
RS_QualitativeBias: Change to NotApplicable
RS_Subpolygon: Change to NotApplicable
RS_Region: Change to NorthAtlantic

My R code to find these values is:
library(icesVocab)
codeTypes <- getCodeTypeList()
RScodeTypes <- codeTypes[grepl('RS_', codeTypes$Key),1]
codeLists<-sapply(RScodeTypes,function(x) NULL)
for (i in RScodeTypes){
  codeLists[[i]]<-getCodeList(i)
}
RSValues <- do.call("rbind", codeLists)
NAvalues <- RSValues[RSValues$Key =='NA',]

**Comment by davidcurrie2001** [comment]
I asked ICES to change the following codes this morning:
Areas_GFCM_GSA: Change NA to NotApplicable
RS_NationalFishingActivity: Change NA to NotApplicable
RS_QualitativeBias: Change NA to NotApplicable
RS_Subpolygon: Change NA to NotApplicable
RS_Region: Change NA to NorthAtlantic

I have updated the documentation as well.
