### ISSUE TITLE
Correspondence between Metier CS, CL and CE

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#32]
Is it supposed to be a strict correspondence by how we encode metier in samples and how that sample is represented in the census data? Frequently we have information to encode a more specific metier when we sample, than what is available in the census. Some guidance on this may be particularly important to non-EU countries.

A motivating example is Norwegian Cod-fisheres by vessels too small for logbooks to be mandated. These catch a large part of the total landed cod, but in sales-notes only gear is reported, not gear details such as mesh sizes.

So when sampling a small gillnetter, I could report it with Metier lvl 6 as for instance: "GNS_DEF_100-119_0_0", but it would be included in CL as "GNS_DEF_0_0_0" (or possibly with estimated fractions in different mesh-size categories). For this particular example, almost all our samples would have mesh-size specification even if they were sampled from the fraction reported in CL as "GNS_DEF_0_0_0". 

I think the field descriptions and possibly the documentation needs to be clarified to give guidance on whether samples should be annotated with the metier used in CL and CE, or whether all available information should be included also in the metier string. Note that we have other fields for the same information, so that it is possible to include all information and report the same metier as used in census.

**Comment by edvinf** [comment]
I have noted also that there are defined metiers with overlapping mesh-size ranges. The same consideration applies to the use of these codes. E.g.:

"GNS_DEF_100-119_0_0", 
"GNS_DEF_110-156_0_0", 
"GNS_DEF_120-219_0_0".

**Comment by edvinf** [comment]
The issue of overlapping codes was also brought up in WKRDB-POP 2 upload log Upload_Log_Template-2020-RDBES-POP2_IFREMER_France_tablesCE-CL (row 14). This upload log makes reference to métier level6  list developped in the context of the "RCG ISSG on Metier issues", and states that this revised list (to be validated in this years RCGs) should contain no overlapping metiers.

**Comment by HenrikK-N** [comment]
The RCG Subgroup on Metier have a final metier list without overlapping metiers, which should be approved by the National Correspondents in September. The metier list have been approved by the RCGs NA NSEA Baltic. So for now we suggest you try to use the final suggested metier list, which can be found at: https://github.com/ices-eg/RCGs/blob/master/Metiers/Reference_lists/RDB_ISSG_Metier_list.xlsx. The following link is for a script which can assign any gear with mesh size etc. to the right metier. There are also documentation and reference lists: https://github.com/ices-eg/RCGs/tree/master/Metiers.
For further questions please ask Josefine at DTU Aqua at: jsv@aqua.dtu.dk
