### ISSUE TITLE
Missing FAO code for Sander lucioperca 

### ISSUE THREAD

**Issue by Ivo-777** [ices-tools-dev/RDBES#33]
Sander lucioperca is not listed in FAO species code list 
https://vocab.ices.dk/?ref=1534

**Comment by davidcurrie2001** [comment]
@Ivo-777 The quickest way to request new codes is to email RDBsupport@ices.dk

**Comment by davidcurrie2001** [comment]
Please email rdbsupport@ices.dk with the new code request.  I will close this issue - please re-open if you have any further questions.
