### ISSUE TITLE
Codes for RS_NationalFishingActivity

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#35]
RS_NationalFishingActivity is the code list for fields in both sample and CL and CE tables, and is currently only populated with a value for missing information (now "NA", to be changed according to issue #31 ). Some users have expressed confusion about this code list. 

Is it supposed to be populated by codes reported by respective countries, and can users already now report to RDBsupport <RDBsupport@ices.dk>?

Are code supposed to be interpreted conditioned on uploading country (in cases when the same national code may be used by several countries) ?

This issue incorporates WKRDBPOP 2 upload log: Upload_Log_2020-RDBES-POP2_Denmark, row number 7, and Upload_Log_Template-2020-RDBES-POP2_IFREMER_France_tablesCE-CL, row number 13.

.

**Comment by davidcurrie2001** [comment]
The country code should be pre-pended to any entries in this list e.g. DK_OTB_.... That way it is clear that the code is only relevant for a particular country.  We updated the description for CEnationalFishingActivity and CLnationalFishingActivity, FOnationalFishingActivity, LEnationalFishingActivity, SAnationalFishingActivity.

**Comment by HenrikK-N** [comment]
Countries should start sending code lists of the NationalFishingActivity to the RDBsupport@ices.dk. (this field is the same as in the current RDB).
