### ISSUE TITLE
code list documentation

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#36]
We are getting several reports about codes being inconsistently listed between field descriptions in the data model and xsd-files / ices vocabulary. We have been redirecting users to the ICES-vocabularies, but the connection between vocabulary and fields are not made explicit, and in some cases it is not trivial to identify. Consolidation of code-lists also causes outdated code-lists to linger an cause some additional confusion. For instance, the stratification fields seem to now be check against YesNoFields.xsd, while RS_Stratification is still available in the repository. The number of reports of this kind in the upload logs from WKRDB-POP 2 calls for a systematic review of code descriptions. To clarify this, and to make it easier to identify what the correct code list is, I suggest we consider two measures:

- Go through and update the basic-checks field with a string identifying the code list for every field in the data model, and add update field descriptions so that they do not specify codes. In cases where the differences between documentation and ICES-vocabulary code-lists is non-trivial (not letter casing, typos etc.), an issue needs to be recorded for the core-group to consider corrections to the ICES vocabulary.

- Add information about the code list checked against in the error messages reported in the upload tool. E.g. for invalid sampling scheme types: "The 'DEsamplingSchemeType' element is invalid. Code not found in 'RS_SamplingSchemeType'".

**Comment by edvinf** [comment]
Some users report confusion for fields when some codes are applicable, and some are not. This happens when codelist are share between fields, such as for RS_CatchCategory. If we do a systematic review of codes, such exceptions should be made clear in field descriptions.

**Comment by edvinf** [comment]
David suggested using the basetype xsd to ensure the correctness of associations between code list and fields, and to partially automate the task.

**Comment by davidcurrie2001** [comment]
I've attached the field names and their types from the BaseTypes.xsd file here.  Hopefully it covers all fields apart from the XXid and XXrecType fields.
[validationData.xlsx](https://github.com/ices-tools-dev/RDBES/files/4851856/validationData.xlsx)

**Comment by davidcurrie2001** [comment]
I'll add a codelist column to the DE tab and we can review - if we're happy we'll assign all the other tabs to people.  We should also check the codes listed in the description fields are correct and review if we actually need them there.

**Comment by davidcurrie2001** [comment]
We also need to think about how the documentation is kept up-to-date when the Data Centre changes range checks or precision etc.

**Comment by edvinf** [comment]
I think this work is also the best way to address issue #16 . If we make sure that the entries in the code list column could be searched on the ICES vocabulary server, I think we have a good enough solution for issue #16 and could close that.

**Comment by davidcurrie2001** [comment]
I have updated the Data Model spreadsheets for the CS data and added a "Vocabulary code type" column which holds the name of the code list.  I haven't checked whether the description is consistent with values in the code list.

**Comment by rix133** [comment]
My small script to check  whether the description is consistent with values in the code list.
``` r
# x is the sheet DE CE,CL etc from the Documentations

library(icesVocab)
#?icesVocab

# extracts from ICES vocabulary 
codeTypes <- getCodeTypeList()
target_codeTypes<-c(codeTypes[grep("RS_", codeTypes$Key),]$Key, "EDMO", "GearType", "ICES_Area", "ISO_3166 (country codes)", "Metier5_FishingActivity", "Metier6_FishingActivity", "SpecASFIS", "SpecWoRMS", "StatRec", "TargetSpecies", "TimeUnit", "Year", "YesNoFields")

codeLists<-sapply(target_codeTypes,function(x) NULL)
for (i in target_codeTypes){
    print(i)
  codeLists[[i]]<-getCodeList(i)
}

colnames(x) <- tolower(colnames(x))
x$lvls <- sapply(x$`vocabulary code type`, function(x){
  codes<-codeLists[[x]]
  if(is.null(codes)){return(NA)}
  return(paste0("\'", codes[["Key"]], "\'", collapse = ", "))
})

xNAs <- ifelse(is.na(x$lvls) & !is.na(x$`vocabulary code type`),x$`vocabulary code type`,NA)

cat(paste0(unique(xNAs[!is.na(xNAs)]),",\n" ))
```

**Comment by HenrikK-N** [comment]
ICES will make a standard procedure of cross-check the changes in vocabularies and the description in the RDBES data model.xlsx. Any discrepancy between the two should be reported to the **RDBsupport@ices.dk**. The 'RS_Stratification' should be substituded by the generic 'YesNoField'.

**Comment by HenrikK-N** [comment]
The ICES Sec. internal procedures will be implemented.

**Comment by luciazarauz** [comment]
As a suggestion, would it be possible to identify somehow RDBES codes in the list of IcesVocab, so that they can be filtered at once? in the code shared by rix133 the variables are selected by name, but I find that this way it is difficult to ensure that you catch all the codes that you need. Thanks
 
(not sure if this comment should go in a different issue..)

**Comment by rix133** [comment]
> As a suggestion, would it be possible to identify somehow RDBES codes in the list of IcesVocab, so that they can be filtered at once? in the code shared by rix133 the variables are selected by name, but I find that this way it is difficult to ensure that you catch all the codes that you need. Thanks
> 
> (not sure if this comment should go in a different issue..)

I updated the codelist downloads to include the new codes its here:

```
#' Import Most Recent ICES codelists
#'
#' @param save2File should it be saved
#' @param savedir directory to save to
#'
#' @return the codeLists if assigned
#' @export
#'
#' @examples
refreshICESCodeList <- function(save2File=F, savedir="./"){
  #?icesVocab
  
  # extracts from ICES vocabulary 
  codeTypes <- icesVocab::getCodeTypeList()
  target_codeTypes<-c(codeTypes[grep("RS_", codeTypes$Key),]$Key,"EDMO", 
                      "GearType", "ICES_Area", "Areas_GFCM_GSA", "ISO_3166",
                      "ISO_3166 (country codes)", "Metier5_FishingActivity",
                      "Metier6_FishingActivity", "SpecASFIS", "SpecWoRMS", 
                      "StatRec", "TargetSpecies", "TimeUnit", "Year", 
                      "YesNoFields", "SamplingSchemeType",
                      "RegDisCategory", "CommercialSizeCategoryScale",
                      "BycatchMitigationDevice","Harbour_LOCODE",
                      "Sampler", "TimeUnit", "SelectionMethod",
                      "ReasonForNotSampling", "BycatchMitigationDeviceTarget",
                      "SelectionDevice","DurationSource", "ObservationCode",
                      "StateOfProcessing","Presentation","SpecimensState",
                      "CommercialSizeCategoryScale","SEXCO","SamplingUnit",
                      "METOA","BiologicalMeasurementType","SampleType",
                      "ValueUnitOrScale","MeasurementCertainty", "Quarter",
                      "Month", "Areas_GFCM_GSA","ObservationActivityType",
                      "ObservationMethod"
                      )
  codeLists<-sapply(target_codeTypes,function(x) NULL)
  for (i in target_codeTypes){
    print(i)
    val<-try(icesVocab::getCodeList(i), T)
    if(class(val) == "try-error") print(paste("Error geting codeList for", i))
    else codeLists[[i]]<- val
  }
  
  
  # save
  if(save2File){
    save(codeLists, file=paste0(savedir,"RDBES_codeLists.rData"))
  }
  invisible(codeLists)
}
```

Also I updated the codelist cheking:

```
checkCodeList <- function(codeName, codeLists, codes, tbl){
  code <- codes[codeName]
  validCodes <- codeLists[[code]]$Key
  data<-unique(tbl[[codeName]])
  if(length(data) < 2){
    if(is.null(data)) stop(paste("Column", codeName, "missing! Aborting!"))
    #if mandatory fields are ok and data is NA the codes don't have to be cheked
    if(is.na(data)) return(NULL)
  }
  invalidCodes <- setdiff(data, validCodes)
  if(length(invalidCodes)>0) {
    warning(printErrorMsg(code, codeName, invalidCodes, validCodes))
    {NULL}
    #codeLists[[code]]
  }
  else{NULL}
  
}
```

```
checkCodeLists <- function(tbl, struct, codeLists) {
  errors <- F
  codeNames <- setNames(as.character(struct$`vocabulary code type`), 
                        struct$`field name`)
  codeNames <- codeNames[!is.na(codeNames)]
  
  res <- sapply(names(codeNames), checkCodeList, codeLists, codeNames, tbl)
  res <- res[lapply(res, is.null) == F]
  if(length(res) == 0){
    return("ICES codelist check OK!")
  }
  res
  
}
```

Then Im I'm using this to check if all the codes in data are OK:

xlsxFpath is the documentacion exel file
tblname is the sheet name

```

struct <- readxl::read_excel(xlsxFpath, sheet = tblName)
  names(struct) <- unifyStructColNames(names(struct))
  struct["field name"] <- fixDocumentationColumn(struct["field name"])
  #remove columns not in format 
  struct <- struct[struct["field name"] !="",]
  struct["vocabulary code type"] <- fixCodeTypes(struct["vocabulary code type"])
  
  
  #fuctions to check uniqe keys and data types 
  #checkColumns(tbl, struct)
   #checkUniqueKeys(tbl, struct)
  
#fuctions to check mandatory fields
#print("Cheking mandatory fields...")
  #checkRes <- checkMandatoryFields(tbl, struct, ...)
  #cat(paste("",tblName,checkRes, "\n"))

  print("Cheking code lists...")
  checkRes <- checkCodeLists(tbl, struct, codeLists)
  cat(paste("",tblName,checkRes, "\n"))

#some helper funcions to fix documentation  errors 
# most of those are fixed allready
unifyStructColNames <- function(cNames){
  cNames <- tolower(gsub("[^[:alnum:] ]", "", cNames))
  cNames[cNames == "req"] <- "required"   
  cNames
}

fixDocumentationColumn<-function(colData){
  colData[colData=="CEscientificFishingDayseffortRSE"] <- "CEscientificFishingDaysRSE"
  colData[colData=="CLscientificWeightLandingsRSE"] <- "CLscientificWeightRSE"
  colData[colData=="CLscientificWeightLandingQualitativeBias"] <- "CLscientificWeightQualitativeBias"
  #remove columns not in format 
  #colData[colData=="CEcommercialEffort"] <- ""
  #colData[colData=="CLcommercialLanding"] <- ""
  
    
  return(colData)
}

fixCodeTypes <- function(colData){
  colData[colData=="BycatchMitigateDevice"] <- "BycatchMitigationDevice"
  colData[colData=="RS_incidentialByCatchMitigationDevice"] <- "BycatchMitigationDevice"
  colData[colData=="LOCODE_Harbour"] <- "Harbour_LOCODE"
  colData[colData=="Harbor_LOCODE"] <- "Harbour_LOCODE"
  colData[colData=="RS_DataTypeForScientificWE"] <- "RS_DataTypeOfScientificWE"
  colData[colData=="RS_DataSourceForScientificWE"] <- "RS_DataSourceOfScientificWE"
  
  return(colData)
}
```

maybe it helps, for me this has been useful for not getting errors on upload and identify inconsnsitencies between documentation and the RDBES system.

**Comment by luciazarauz** [comment]
thank you!
