### ISSUE TITLE
Clarification SAcommSizeCatScale and SAcommSizeCat

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#37]
The description of SAcommSizeCat states that the value is optional for "unsorted", but the code-list for neither SAcommSizeCat or SAcommSizeCatScale contains the code "unsorted". These are both optional fields, and the description could be rephrased to reflect that, or the code "unsorted" could be added to SAcommSizeCatScale.

This issue incorporates issue from WKRDB-POP 2 upload log: Upload_Log_2020-RDBES-POP2_MI_Ireland, row 22.

**Comment by davidcurrie2001** [comment]
Updated descriptions of SAcommSizeCatScale and SAcommSizeCat.
