### ISSUE TITLE
Restrictions on SAsequenceNumber

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#38]
The description of SAsequenceNumber and comparison with how sequenceNumber works for other tables indicate that this number must be unique at its level in the hiearchy (within strata/cluster). The upload tool seems to check for global uniqueness. If this restriction is intended, we need to improve the documentation a bit. Otherwise this should be reported as a bug and error checking should be relaxed.

**Comment by davidcurrie2001** [comment]
We need to clarify with the Data Centre what the uniqueness constraint is - I'll do this.

**Comment by davidcurrie2001** [comment]
Related to #51

**Comment by davidcurrie2001** [comment]
Currently the uniqueness constraint for SAsequenceNumber is that it has to be unique within its value of SS i.e.

Key 2

- SSid
- SAsequenceNumber

**Comment by davidcurrie2001** [comment]
ICES have now added SAsequenceNumber to UK1 and removed UK2 - please can you check if this uniqueness issue is resolved.

**Comment by edvinf** [comment]
If I re-use sample numbers for different samples, taken from different fishing operations, and what I consider to be different species-selections, it seems that duplication checks passes. But I get an error on the "sub sample check". This seems to be a different check than the duplication check, and these restrictions are not described in the field description for SAsequenceNumber. I think we should incorporate the restrictions from the sub sample check in the field description, but I don't know whether they need to be unique within a year, within a sampling scheme for a year, or something more narrow.

**Comment by HenrikK-N** [comment]
We would still need the UK2 to ensure that the SAparentSequenceNumber referes to only one record specified by the SAsequenceNumber, SSid (SpeciesSelectionID). The 'sub sample check' should just be checking that the refered SAsequenceNumber in the SAparentSequenceNumber exists. ICES will add the UK2 again and check the 'sub sample check'.

**Comment by HenrikK-N** [comment]
UK2 have been added again.
