### ISSUE TITLE
Precision for sampling probabilities

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#39]
We need to address what is an appropriate precision for inclusion and selection probabilities. Currently, this is restricted to two digits, which is clearly to coarse for real data.

As the number of decimals are checked when uploading. The field descriptions need to specify the number of digits allowed. This is not currently included.

For reference, the precision issue was discovered through RDBES support issue:  I2006-088 - NA

**Comment by edvinf** [comment]
Some considerations for this issue.

Sampling probabilities can in principle be arbitrarily low, and provisions for unequal probability sampling are best made if we allow as much precision as technically possible. Keeping 14 decimals should keep typical machine precision in R at arms length (usually in the order of e-16). If we need to restrict it further, we may make a tentative restriction and perhaps investigate the consequences of restricting this precision during WKRDB-EST 2.

If there are some kind of technical requirement to reduce the number of allowed decimal points, we should identify some reasonable bound based the largest national census we can identify. With the hierarchies currently defined, the largest number of PSUs we may encounter probably arises from either a census of fishing operations or onshore-events with port-days. An unstratified, all-species sampling of catches in the Norwegian fleet would give a census with size in 6 digits. The order of magnitude would arise from a strata with 1000 ports operational all year. Equal probability sampling of such sampling frames would suggest around 8 digits for selection probabilities, so I'd suggest that 8 digits could be a tentative restriction on precision.

**Comment by davidcurrie2001** [comment]
We will ask the Data Centre to increase all the probability fields to tDecimalPrec10.  If users still have precision problems then a mail can be sent to rdbsupport@ices.dk to increase the precision.

**Comment by edvinf** [comment]
10 decimal precision is implemented. Performed test for FO table.
