### ISSUE TITLE
Clarification of official numbers CL and CE

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#40]
As official weights or effort variables may in some cases be estimated, we may need to clarify description where this term is used in the CL and CE data model. This was brought up in upload logs after WKRDB-POP 2 and the term "Control regulation data" was suggested in stead.

This issue incorporates issue reported in upload log Upload_Log_Template-2020-RDBES-POP2_IFREMER_France_tablesCE-CL, row 5.

**Comment by davidcurrie2001** [comment]
Updated description for CLdataTypeOfScientificWeight and CEdataTypeForScientificEffort.  Need to let ICES know to update the code list description.

**Comment by mrska** [comment]
Descriptions sent to ICES.

**Comment by HenrikK-N** [comment]
Updates have been made.
