### ISSUE TITLE
Clarification of fishing technique

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#41]
On CL and CE fishing technique is defined with reference to FDI data call. More specific address for definition is needed, or additional field documentation. In particular it should be made clear that this is a vessel property, constant for year, and not a property of catch. That is that fishing techniques that indicate gear use, should not aggregate catches of that gear, but vessels with that gear as their dominant gear.

This issue incorporates issue in WKRDB-POP 2 upload log: Upload_Log_Template-2020-RDBES-POP2_IFREMER_France_tablesCE-CL, row 16.

**Comment by davidcurrie2001** [comment]
Description in the CE/CL data model has been updated.
