### ISSUE TITLE
Vessel length categories

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#43]
Some user have reported the need to provide finer resolution on vessel length than what is currently provided in RS_VesselLengthCategory. If introduction of finer detail is necessary, it would be nice to incorporate them right away, to avoid overlapping code options in the future. Specifically the ranges <6m and 6<8m have been requested. 

This issue incorporated WKRDB-POP 2 upload log: Upload_Log_Template-2020-RDBES-POP2_IFREMER_France_tablesCE-CL, row 15.

These suggestions have been made to support potential future use, and is not required for the 2020 test data call.

**Comment by davidcurrie2001** [comment]
Will discuss after the test data call

**Comment by josefineegekvist** [comment]
Include vessel ranges <6 and 6-8.
Current categories: <8, 8-<10, 10-<12, 12-<15, 15-<18, 18-<24, 24-<40, 40<, Unknown.
Change to: <6, 6-<8, 8-<10, 10-<12, 12-<15, 15-<18, 18-<24, 24-<40, 40<, Unknown

**Comment by davidcurrie2001** [comment]
Draft entry for FAQ on this topic:

"What should I do if need to upload CL/CE data when I don't know the exact vessel lengths for some segments of the data?

Usually you will know the specific vessels that data relates to and can then categorise the vessel lengths in line with the RS_VesselLengthCategory code list.  However, there can be cases where this is not possible e.g. if you have official estimates of landings from all vessels under 10m then you will not be able to correctly categorise them using the RS_VesselLengthCategory code list.  There are two distinct cases to consider here:
Case 1: you know nothing about the vessel lengths that the landings or effort data relates to.  In this case use the "Unknown" value from the RS_VesselLengthCategory code list
Case 2: you know something about the vessel lengths, but that information does not fit with the RS_VesselLengthCategory values (e.g. you know that all vessels are under 10m).  In this case choose the highest category from RS_VesselLengthCategory that is less than the largest vessel length in your data e.g. if your data all comes from under 10m vessel then use the 8-<10 category, or if your data all comes from under 12m vessels then use the 10-<12 category."

**Comment by davidcurrie2001** [comment]
FAQ added to documentation in ices-taf/RDBES_Core_Group

**Comment by josefineegekvist** [comment]
Discussed 11/01/2022 by RDBES CE CL subgroup. The issue seem to be solved and can be closed.
Davids Draft entry for FAQ on this topic should be added to the documentation.

**Comment by josefineegekvist** [comment]
The text is inserted in the documentation: https://github.com/ices-taf/RDBES_Core_Group/blob/master/RDBES%20Documentation%20of%20CL%20CE.docx

**Comment by josefineegekvist** [comment]
Moved updated from the documentation CL CE to the complete documentation of the data model. Agreed at core group meeting 20220309 to close the issue after that.
