### ISSUE TITLE
range checks for effort

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#44]
We need to specify reasonable ranges for effort in CE. Some users have reported that current range checks are too restrictive, for instance for CEscientificSoakingMeterHour and CEofficialSoakingMeterHour.

This issue incorprorates issue form WKRDB-POP 2 upload log: Upload_Log_Template-2020-RDBES-POP2_ltu, number 3.

**Comment by davidcurrie2001** [comment]
The general approach to these types of problems is to log a call with rdbsupport@ices.dk detailing what range is required.
