### ISSUE TITLE
Field description exclusiveEconomicZoneIndicator

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#45]
The fields CEexclusiveEconomicZoneIndicator and CLexclusiveEconomicZoneIndicator are mandatory, but the field description states that they are only relevant for EU-countries exporting data to FDI. It is unclear how non-EU countries should fill this field.

This issue incorporates WKRDB-POP 2 upload log: Upload_Log-2020-RDBES-POP2_IMR_Norway_Tromso, row 6.

**Comment by davidcurrie2001** [comment]
The fields should be optional in both CE and CL.  We updated CLexclusiveEconomicZoneIndicator to be "O" in the Data model spreadsheet.  We will tell the developers about the change.

**Comment by edvinf** [comment]
All exclusiveEconomicZoneIndicator fields now optional according to updated BaseTypes.xsd (did not perform any test)
