### ISSUE TITLE
stratified clustered sampling, code list RS_Clustering

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#47]
The examples for recording clustered sampling that was recently added to the documentation has revealed a need to distinguish when any stratification is done within a cluster, and when clusters are sampled in a stratified way. I have discussed this with Nuno, who suggested to incorporate this in the code list RS_Clustering. We didn't quite settle the details, but a tentative suggestion would be to extend the code list:

1-Stage
2-Stage
1-Stage stratified cluster selection
2-Stage stratified cluster selection
1-Stage stratified within cluster
2-Stage stratified within cluster

This tentative code list has 6 entries for clarity, but any use of the four latter codes in combination with stratified="No" would in principle suffice to encode unstratified clustered sampling.

**Comment by davidcurrie2001** [comment]
Will discuss later in the summer when people are back from holidays

**Comment by HenrikK-N** [comment]
'1-Stage' and '2-Stage' should be more explicite adding 'unstratified cluster'.

**Comment by nmprista** [comment]
One possibility worth considering may be joining variable "RS_Clustering" and RS_Stratification" into a single variable "RS_StartificationClustering". This to avoid ambiguities like, e.g., RS_Stratification == N and RS_Clustering =="1-Stage stratified within cluster" and so on. 
The code list could then be something of the sort:

- Unstratified, Unclustered
- Stratified only* 
- 1-stage cluster
- 2-stage cluster
- Stratified then 1-stage cluster
- Stratified then 2-stage cluster
- 1-stage cluster, stratified within 1-stage cluster
- 2-stage cluster, stratified within 1-stage cluster
- 2-stage cluster, stratified within 2-stage cluster

*could also be "Stratified, unclustered"

**Comment by HenrikK-N** [comment]
The agreed code list for RS_Clustering is:
N                                                      Desc:' 'N' for No clustering
1C           Desc: 1-stage cluster sampling without stratification
2C           Desc: 2-stage cluster sampling without stratification
S1C         Desc: Stratified sampling of 1 stage clusters
S2C         Desc: Stratified sampling of 2-stage clusters
1CS         Desc: 1-stage cluster sampling followed by stratification of sampling units within the clusters
2CS   Stratified within 2-stage cluster        Desc: 2-stage cluster sampling followed by stratification of sampling units within the clusters

Add check if RS_Stratification = Yes, then error if '1-stage cluster' or '2-stage cluster'. 
Add check if RS_Stratification = No, then error if 'Stratified then 1-stage cluster', 'Stratified then 2-stage cluster', 'Stratified within 1-stage cluster' , 'Stratified within 2-stage cluster'

**Comment by HenrikK-N** [comment]
The codes have now updated.
