### ISSUE TITLE
New codes for FMtype

### ISSUE THREAD

**Issue by Eucrow** [ices-tools-dev/RDBES#48]
The table RS_MeasurementType used to fill the variable FM type has these codes:

- Fork Length
- Head Length
- Tail Length
- Total Length
- Total Live Weight
- Width

But in the case of cephalopods we use the mantle length and in crustaceans we use the cephalothorax length. Would be possible to add codes for this cases?

**Comment by davidcurrie2001** [comment]
The quickest way to add new codes is to email rdbsupport@ices.dk and request them - please let us know if you have any problems doing this, or want us to do it for you.

**Comment by Eucrow** [comment]
Thank you @davidcurrie2001 I just wrote them now.

**Comment by davidcurrie2001** [comment]
Call has been raised with ICES so I will close this issue - please re-open if required.  Thanks.
