### ISSUE TITLE
Hierarchy 5 and Hierarchy 7 look alike in table 1

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#5]
Hierarchy 5 and Hierarchy 7 look alike in table 1. Suggestion is to delete "landing event" from hierarchy 7 to make it more in line with the sampling units and the scheme displayed in annex

**Comment by HenrikK-N** [comment]
We specify that the Hierarchy 7 does not have Landing Event in the estimation hierarchy, and see annex.
