### ISSUE TITLE
descriptions for code list RS_LowerHierarchy

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#50]
The code list for RS_LowerHierarchy does not have descriptions on the ICES vocabulary server. I suggest we add descriptions based on the headers in "RDBES Documentation of the Data Model.docx"

A: Length stratified biological samples 
B: Only length frequency data is taken from sample(s)/subsample(s) 
C: All individuals in the sample/subsample are biologically analyzed
D: No length measurements or biological analyses

Perhaps we could also extend the descriptions to highlight exactly which lower hiearchy tables are to be expected.

**Comment by davidcurrie2001** [comment]
How about:
A: Length stratified biological samples (FM and BV)
B: Only length frequency data is taken from sample(s)/subsample(s) (FM)
C: All individuals in the sample/subsample are biologically analyzed (BV)
D: No length measurements or biological analyses (None)

**Comment by mrska** [comment]
Descriptions sent to ICES.

**Comment by edvinf** [comment]
Thanks. I have verified that descriptions are now in place at https://vocab.ices.dk .
