### ISSUE TITLE
Duplication check SA table with subsampling

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#51]
The duplication check for the SA table is specified so that it does not allow subsampling unless some of the fields specified by UK1 on the SA table is different between the parent sample and the subsample. Subsampling with these fields unchanged between parent sample and subsample is reasonable and should be supported.

The issue is motivated by the case reported in issue: https://github.com/ices-tools-dev/RDBES/issues/49 and can otherwise be reproduced by the following example:

DE,National Routine,NatpilCF,2018,Norwegian fleet > 15 m,Y,13
SD,NO,1351
FO,No,1,U,No,U,Self-Sampling,H,V,Lan,2018-08-02,,2018-08-02,,,58.58333,2.08333,,,,27.4.a,,NA,,,,,PS_SPF,PS_SPF_0_0_0,PS,,0,0,SPF,Unknow,,Ha,,14,,,UPSWOR,38439,,,,,,Y,
SS,1,No,haul,Lan,vol,U,No,U,Self-Sampling,Herring,Y,1,1,1,1,CENSUS,Herring,,,,,,Y,
SA,1,,No,U,126417,,Whole,Dead,Lan,,,,U,,,,NA,,,,,,,,,Basket,350000000,14120,,,,,SYSS,1,D,Self-Sampling,Y,,,,
SA,2,1,No,U,126417,,Whole,Dead,Lan,,,,U,,,,NA,,,,,,,,,Kg,14120,7120,,,,,SRSWOR,1,C,Self-Sampling,Y,,,,
BV,1,N,U,TotalLength,300,mm,,,67,67,,,SRSWOR,1,Observer
BV,1,N,U,Age,9,Year,Otolith,,67,49,,,SRSWOR,1,Observer
BV,1,N,U,WeightLive,290,g,,,67,67,,,SRSWOR,1,Observer

**Comment by davidcurrie2001** [comment]
We think is SAsequenceNumber was added to the UK1 then it would solve the problem.  I will email rdbsupport@ices.dk and ask for it to be included.

**Comment by Eucrow** [comment]
I just try to upload our data with a similar case and it works. I suppouse the problem is solved, right? :)

**Comment by davidcurrie2001** [comment]
I just checked with ICES and there are 2 uniqueness keys currently applied:

Key 1

- SSid
- SAspeciesCode
- SAspeciesCodeFAO
- SApresentation
- SAcatchCategory
- SAlandingCategory
- SAcommSizeCatScale
- SAsex

Key 2

- SSid
- SAsequenceNumber

So, if you have a sample and a sub-sample with the same species/size/presentation/etc it will currently fail validation.  Key 1 is not the same as currently described in the Data Model so ICES will revise it.  I will ask whether the SAsequenceNumber can also be added to Key 1.

**Comment by davidcurrie2001** [comment]
ICES have now added SAsequenceNumber to UK1 and removed UK2 - please can you check if this sub-sampling issue is resolved.

**Comment by edvinf** [comment]
Yes. Works for me now. Also seems to work for @Eucrow , so I'll close the issue.

**Comment by HenrikK-N** [comment]
By adding SAsequenceNumber to UK1, it will not be possible to ensure duplicate data was not inserted, which was the originally reason for the UK1:

- SSID
- SAsequenceNumber
- SAspeciesCode
- SAspeciesCodeFAO
- SApresentation
- SAcatchCategory
- SAlandingCategory
- SAcommSizeCatScale
- SAcommSizeCat
- SAsex

Substitute SAsequenceNumber with SAparentSequenceNumber - then it should work

So I suggest we remove SAsequenceNumber from UK1, and add SAparentSequenceNumber to UK1 instead, that should make it possible to ensure duplicate data was not inserted and also allow for Subsampling having the same UK1-data as the parent. 
This will affect the second option in https://github.com/ices-tools-dev/RDBES/issues/70 if we want that, if so we can add stratification to the UK1, then it is possible to record subsamples like option 2.
Please reply fast to come to a conclusion which is needed for data uploads.

**Comment by nmprista** [comment]
related to https://github.com/ices-taf/RDBES_Core_Group/issues/56

**Comment by HenrikK-N** [comment]
The two unique keys have been implemented again, and it is working fine.
