### ISSUE TITLE
LEgsaSubarea and SAgsaSubarea doesn't accept NA value (or empty field)

### ISSUE THREAD

**Issue by Eucrow** [ices-tools-dev/RDBES#53]
Right now those fields are mandatoty but doesn't accept NA value or empty field, while the RDBES model documentation says:
'GSA subarea, mandatory for FAO area 37 (Mediterranean and Black Sea). (Use 'NA' if not fishing in the area)'
returning this error:

`5 | 'LEgsaSubarea' | NA | Enumeration | The 'LEgsaSubarea' element is invalid`

I think that, until now, the application didn't throw that error. Maybe is related with #31 issue?

This extract reproduce the error:
```
DE,National Routine,NatRouCF,2019,IEO_M_BC_AC,Y,5
SD,ES,353
OS,1,ESGIJ,Yes,ESGIJ,2019-02-04,,Q1,No,U,Observer,,,14,3,,,NPEJ,1,Market,,,,,,Y,
FT,204876,,No,U,No,U,Observer,On-Shore,,,,,ESGIJ,2019-02-04,,,,,,NPEJ,201900431,,,,,,Y,
LE,204876,No,1,,U,No,U,Observer,N,Lan,ESGIJ,Port,ES,2019-02-04,,EU,27.8.a,21E5,NA,,,OTB_DEF,OTB_DEF_>=70_0_0,OTB,,,,,Unknow,,,,,,NPEJ,201900431,,,,,,Y,,Yes
SS,1,No,sort,Lan,vol,U,No,U,Observer,IEO_M_SAP_DCF,N,,,,,CENSUS,IEO_M_SAP_DCF,,,,,,Y,
```

**Comment by davidcurrie2001** [comment]
Yes, I think it is my fault - I asked ICES to make the following change this morning but haven't updated the documentation yet:
Areas_GFCM_GSA: Change NA to NotApplicable

Can you check if "NotApplicable" is accepted?

**Comment by Eucrow** [comment]
Thank you @davidcurrie2001 , with "NotApplicable" it works.

**Comment by davidcurrie2001** [comment]
Great - I'll close this call and update the documentation now.
