### ISSUE TITLE
CL Documentation typos

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBES#54]
Code RS_dataSourceOfScientificWE wrong in CL it should be RS_DataSourceOfScientificWE as in ices code lists

Description of CLtotalOfficialLandingsValue states "Please report the data source in the field 'CLdataSourceOfScientificWeight'"

Shouldn't it be CLdataSourceLandingsValue where it is reported

**Comment by rix133** [comment]
Other not matching codes include:
RS_nationalFishingActivity,
RS_deepSeaRegulation

likely a first word capitalization issue

**Comment by davidcurrie2001** [comment]
I have just updated the code list names for CE and CL from the XSD files so hopefully should be fixed now - please check that you're happy with the update.

**Comment by davidcurrie2001** [comment]
I have also just updated the description for CLtotalOfficialLandingsValue

**Comment by rix133** [comment]
Thanks David, I was happy before also :) just wanted to fix it for others.

**Comment by rix133** [comment]
the error in the  Description of CLtotalOfficialLandingsValue is back!

**Comment by HenrikK-N** [comment]
We will fix it

**Comment by HenrikK-N** [comment]
The description of CLtotalOfficialLandingsValue now refers to CLdataSourceOfScientificValue.
