### ISSUE TITLE
CE documentation typos

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBES#55]
RS_DataSource**For**ScientificWE - no such code in code lists but RS_DataSource**Of**ScientificWE  exists

**Comment by rix133** [comment]
All codes  from CE table that I could not find in the Ices code lists now:
RS_DataTypeForScientificWE,
RS_DataSourceForScientificWE,
RS_nationalFishingActivity,
RS_incidentialByCatchMitigationDevice,
RS_deepSeaRegulation,
RS_qualitativeBias

the For vs Of is Obvious others might be also Caps problems

**Comment by davidcurrie2001** [comment]
I have just updated the code list names for CE and CL from the XSD files so hopefully should be fixed now - please check that you're happy with the update.

**Comment by rix133** [comment]
Thanks David, I was happy before also :) just wanted to fix it for others.
