### ISSUE TITLE
New variables in SA table apparently considered in other tables

### ISSUE THREAD

**Issue by luciazarauz** [ices-tools-dev/RDBES#56]
Hello,

I have found that in table SA, there are some variables related with the area, metier, mesh size.. which in Hierachy 5 are already covered in table LE.
I was thinking in leaving them empty to avoid double reporting. Is that OK? which is your prefered option?

**Comment by davidcurrie2001** [comment]
When you definitely know the area/gear etc. that the sample was taken from then you should always fill in these values on the SA table.  The area/gear etc on the LE table are the **dominant** values (e.g. if a landing consists of catches from multiple areas then you just choose the dominant area for the LE record).  There will clearly be times when the area/gear values on the LE table and the SA table are the same and it is fine to record the same values in both tables.
The only time you wouldn't fill in the area/gear etc on the SA table is if you **don't** know the specific values for that sample e.g. if a trip fished in multiple areas but you don't know which area your sample was taken from.  In that case you would still fill in the dominant values on the LE table, but leave the values blank on the SA table.

**Comment by luciazarauz** [comment]
ok, it is clear now. thanks

**Comment by davidcurrie2001** [comment]
Ok, I will close this issue.
