### ISSUE TITLE
RS_SamplingScheme codelist

### ISSUE THREAD

**Issue by luciazarauz** [ices-tools-dev/RDBES#57]
Hello,
it's me again.. :-)

For the variable DEsamplingSchemeType, how shall we do to get the National codes included in the RS_SamplingScheme codelist codelist?

Thanks

**Comment by davidcurrie2001** [comment]
Hi,  to add entries to the code list RS_SamplingScheme which is used by DEsamplingScheme just email rdbsupport@ices.dk and request the new codes.  Please use this same procedure for adding values to any other code lists as well.

**Comment by davidcurrie2001** [comment]
I will close this issue now - please re-open if you need any further clarification
