### ISSUE TITLE
SpecASFIS and SpecWoRMS codelists

### ISSUE THREAD

**Issue by luciazarauz** [ices-tools-dev/RDBES#58]
Hello,

we have sampled species which are not in the codelist specASFIS and SpecWoRMS
How can we do to update the code list?

The codes not matching are the following:

ASFIS:
 "BIB" "BRB" "RSE" "GUM" "MGR" "SBA" "SOS" "VMA" "CTB" "DEC" "SHR" "SNQ" "SSB" "SWA" "USB" "BON" "CBR" "UCA" "USI" "CTZ" "MKG" "SBZ" "RPG" "SBS" "MUF" "BLT" "MLR" "ALB" "BET" "POD" "CET" "COB" "SLM" "POA" "GUN" "TRG" "ARY" "CBC" "GAR" "BFT" "SKJ" "MOX" "SAU"

WORMs:
127248 127007 127054 273962 127052 127246 127041 127011 151501 127261 127015 127028 126783

Thanks

**Comment by davidcurrie2001** [comment]
Hi @luciazarauz 
Generally to request new entries to a code list email rdbsupport@ices.dk and request the new codes.

**Comment by luciazarauz** [comment]
ok, thank you very much

**Comment by davidcurrie2001** [comment]
I will close this issue - please re-open if you need any further clarification.
