### ISSUE TITLE
VD variables for length, tonnage and power not optional

### ISSUE THREAD

**Issue by luciazarauz** [ices-tools-dev/RDBES#60]
VD variables: VDlength, VDpower, VDtonnage and VDtonUnit are described as optional in the data model table. However when uploading the data it gave errors and we had to fill them in. When filling them in, the file was uploaded correctly

**Comment by davidcurrie2001** [comment]
In the XSD file they are correctly defined as optional and when I remove the values in my data I can still successfully upload the HVD file.  I think you might have a different issue in your data - are you able to share the file which would not upload?

**Comment by HenrikK-N** [comment]
I can confirm that there are records in the RDBES database, which does not have the the VD variables: VDlength, VDpower, VDtonnage and VDtonUnit filled in. I suggest you take a screen shot and send it to the RDBsupport@ices.dk, if you see the problem again.
