### ISSUE TITLE
mandatory status for SAgsaSubarea

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#61]
The area codes and gear parameters at the SA table are defined to be exact codes for the sample, as opposed to area codes on higher level sampling units such as FT or LE which are defined as dominant code for trip or landing. When exact codes are not known the area codes on SA will be filled as NA. They are therefore all defined as optional, except the SAgsaSubarea. I think we should consider making this optional as well, since "NotApplicable" is defined as fishing outside FAO area 37.

**Comment by davidcurrie2001** [comment]
I agree.  I don't think it will make much difference in practice but its odd to have this inconsistency.

**Comment by HenrikK-N** [comment]
The SAgsaSubarea can be made optional after October 2020.

**Comment by HenrikK-N** [comment]
The SAgsaSubarea have be made optional.
