### ISSUE TITLE
Problem with two different passive gears during the trip

### ISSUE THREAD

**Issue by Ivo-777** [ices-tools-dev/RDBES#62]
I have a question about coastal fishery problem in Latvia. Wery often we have situation then observer during one trip is checking two different passive gears. Information about catches is collected separately for each fishing gear. For existing FishFrame Database we are uploading this information as two separate trips. It is not possible for RDBES format where screening programme checks the combination of vessel & data & departure time and find that vessel at the same time participates in two trips. Maybe someone can help me with an idea of how to solve this problem? Our options are to write a different departure time for the second trip.

**Comment by edvinf** [comment]
Thank you for your question @Ivo-777 . Which hierarchy have you been using for these samples ?

**Comment by Ivo-777** [comment]
I am using hierarchy 1 for these data.

**Comment by HenrikK-N** [comment]
I suggest to record the two different fishing gears under the one Fishing Trip but in two different Fishing Operations, this also works for hierarchy 1. The two different fishing operations have different; start time, statistical rectangles and metier level 6 (fishing gear). I do not see a problem in two different stratifications regarding active and passiv gears under the same trip.

**Comment by Ivo-777** [comment]
Thanks, Henrik for Your proposal. I will prepare data as You suggested.

**Comment by Ivo-777** [comment]
Thanks, Henrik for Your proposal. I will prepare data as You suggested.


Best regards,


Ivo

________________________________
No: Henrik Kjems-Nielsen <notifications@github.com>
Nosūtīts: otrdiena, 2020. gada 4. augusts 16:16:45
Kam: ices-tools-dev/RDBES
Kopija: Ivo Šics; Mention
Tēma: Re: [ices-tools-dev/RDBES] Problem with two different passive gears during the trip (#62)


I suggest to record the two different fishing gears under the one Fishing Trip but in two different Fishing Operations, this also works for hierarchy 1. The two different fishing operations have different; start time, statistical rectangles and metier level 6 (fishing gear). I do not see a problem in two different stratifications regarding active and passiv gears under the same trip.

**Comment by HenrikK-N** [comment]
I can see you have uploaded, so I expect this is fine.

**Comment by Ivo-777** [comment]
Yes, I uploaded vessel list for coastal fishery segment, but I am not sure what happened with vessel lists for other segments previously uploaded. Screening program asked that to do, overwrite data or cancel. I am not sure what happening if I upload data by segments, not as on file for all Latvia data.


Ivo

________________________________
No: Henrik Kjems-Nielsen <notifications@github.com>
Nosūtīts: trešdiena, 2020. gada 5. augusts 14:16:17
Kam: ices-tools-dev/RDBES
Kopija: Ivo Šics; Mention
Tēma: Re: [ices-tools-dev/RDBES] Problem with two different passive gears during the trip (#62)


I can see you have uploaded, so I expect this is fine.
