### ISSUE TITLE
Wrong duplicate field check it TE table

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBES#63]
While uploading the duplicate field check raises an error:
Table:  TE
Key Fields:  TEstratification, TEinclusionProb 
The data TEstratification has only Yes as values and TEinclusionProb  is empty as the selection method is NPAH 
It seems strange to me that these two fields cannot be same and looking at the Data model description in the xlsx file those fields have not been declared as unique keys, so my guess is that the duplicate field check is wrong or am I missing something in the documentation?

**Comment by davidcurrie2001** [comment]
You're right - the check has been implemented incorrectly.  I have logged a call with the ICES Data Centre to look at this and will let you know once it is resolved.

**Comment by davidcurrie2001** [comment]
I think ICES have now resolved this - can you see if it has fixed your issue?

**Comment by rix133** [comment]
yes this is resolved
