### ISSUE TITLE
SS table duplicate field check error

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBES#64]
A more complex duplicate field check issue. The check Gives an Error:
Constraint Name: **SS4**
Table:  **SS**
Key Fields:  SSobservationType, SSobservationActivityType, SScatchFraction
Parent Field: **TErecord**
The unique keys are the right ones (SSobservationType, SSobservationActivityType, SScatchFraction)
However, I'm trying to submit **H8** witch has the sequence of tables TE->VS->LE->SS->SA and one of my TE records has several landing events (LE) and all are sampled. My gues is taht the parent field to check should be LErecord not TErecord in that case.
 **H9** on the other hand has TE->SS->SA table sequence so  for **H9** such a check (TE->SS) seems logical. 

If this check is right and **H8** should have unique SS records for each TE then it would be good to somehow point that out in the documentation.

**Comment by HenrikK-N** [comment]
We are very soon looking into this issue. Technical issues like this should be send to the RDB@support.dk.

**Comment by HenrikK-N** [comment]
The duplicate field check issue is not corrected.
