### ISSUE TITLE
Problem with "Number of fraction trips" in Commercial effort table

### ISSUE THREAD

**Issue by Ivo-777** [ices-tools-dev/RDBES#65]
Hai! 
I have a question about the field "Number of fraction trips" in Commercial effort table. It is a mandatory field with decimal number type. According to the manual, the minimum allowed value is 0.01.  I checked Latvia data for 2019 in Baltic Sea, and find seven records only when ship worked in 2 rectangles during the trip. The screening programme doesn't allow to use 0 for this field or leave this field blank.

**Comment by HenrikK-N** [comment]
Hi Ivo
Have you read the documentation with the example under 'Fields in Commercial Effort (CE) data format', if not please do so. If you have a trip fising in 2 statistical rectangles most likely you would not have a value lower that 0.01 for one of the stat. rect. Please return if you are sure that you calculate a number lower than 0.01, when you follow the example on page 8 in the documentation 'Fields in Commercial Effort (CE) data format'.

**Comment by Ivo-777** [comment]
Dear Henrik,

Thanks for Your information. I solved my problem with Fraction trips in Commercial effort file.
I still have problems with missing Asfis and Worms codes. I can't find Asfis FAO codes for Acipenser sturio, Leuciscus idus, Leuciscus leuciscus, Cyprinus carpio, Tinca tinca, Lampetra fluviatilis, Oncorhynchus mykiss, Hyperoplus lanceolatus. I can't find Worms codes for Acipenser sturio, Aspius Aspius,  Leuciscus idus and Leuciscus leuciscus. I have problem with Gasterosteus aculeatus also. Checking programme finds that FAO code "GTA" is not correct for this species although the code is correct.

Best regards,

Ivo


________________________________
No: Henrik Kjems-Nielsen <notifications@github.com>
Nosūtīts: pirmdiena, 2020. gada 31. augusts 10:36:37
Kam: ices-tools-dev/RDBES
Kopija: Ivo Šics; Author
Tēma: Re: [ices-tools-dev/RDBES] Problem with "Number of fraction trips" in Commercial effort table (#65)


Hi Ivo
Have you read the documentation with the example under 'Fields in Commercial Effort (CE) data format', if not please do so. If you have a trip fising in 2 statistical rectangles most likely you would not have a value lower that 0.01 for one of the stat. rect. Please return if you are sure that you calculate a number lower than 0.01, when you follow the example on page 8 in the documentation 'Fields in Commercial Effort (CE) data format'.

**Comment by HenrikK-N** [comment]
Dear Ivo.
I am glad to hear you have solved you problem with the Fraction trips in CE. 
Regarding missing species codes please send an email with the species requested to RDB@support.dk
Br Henrik

**Comment by davidcurrie2001** [comment]
^ rdbsupport@ices.dk
