### ISSUE TITLE
error donwloading data 

### ISSUE THREAD

**Issue by Eucrow** [ices-tools-dev/RDBES#66]
I'm trying to download our data previously uploaded in RDBES by menu "Data Handling" --> "Download Data", but I always get this unspecific error:

"An error occurred
Please send an email and describe the problem.
Back to RDBES home page"

I tried the CS, VD and SL, but all of them have the same problem.

Thanks,
Marco.

![image](https://user-images.githubusercontent.com/10269446/91721272-c7ed5e80-eb98-11ea-81e7-57d17d02f8c8.png)

**Comment by HenrikK-N** [comment]
Hi Marco

That is right there was an error in the download, but it has now been solved.

Br Henrik
