### ISSUE TITLE
LEencryptedVesselCode description in Data Model.xlsx incomplete

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBES#67]
While uploading the following check fails:
**Hierarchy Dependent Check Failed**
 SL and VD lookup codes must or must not be reported depending on the hierarchy. 

* DataType: **LE**
* Field: **LEencryptedVesselCode**
* Must be provided?: **must not provide code**

I guess this check is OK. However the documentation lacks this info.

The "RDBES Data Model.xlsx" sheet "Landing Event" states "Required" field as **M** (should be likely **M/O**) and the description does not mention the hierarchy dependency.

**Comment by rix133** [comment]
OK there is another related issue when I remove the values **LEencryptedVesselCode** (i.e. set them to empty) I get the following error:
**Lookup Data Check Failed**
Lookup not found in DataBase for some fields. The fields are all **LEencryptedVesselCode**

**Comment by HenrikK-N** [comment]
We are at the moment looking into this issue, the core group have to specify if the XXencryptedVesselCode in all tables should be mandatory or not.

**Comment by HenrikK-N** [comment]
It has be decided that the XXencryptedVesselCode in all tables should be mandatory. There is one exception and that is when LEmixedTrip is 'Y'/yes.
