### ISSUE TITLE
Clarification of description for CEscientificFishingDays

### ISSUE THREAD

**Issue by jcraigMS** [ices-tools-dev/RDBES#68]
Hi,

In the description for CEscientificFishingDays data model it says this 'Can be equal to official days at sea.'
Can you confirm that this should read 'Can be equal to official **fishing** days at sea.' ?

Thank you,
Jess

**Comment by HenrikK-N** [comment]
In the description for CEscientificFishingDays data model it should say 'Can be equal to official fishing days'. It will be updated.
Br Henrik

**Comment by jcraigMS** [comment]
Thank you
