### ISSUE TITLE
Clarification of description for CEnumberOfDominantTrips - 'most fishing' by landWt?

### ISSUE THREAD

**Issue by jcraigMS** [ices-tools-dev/RDBES#69]
Hi,

In the description of CEnumberOfDominantTrips the area/rectangle/métier/month with the 'most fishing' is used. 
Can you please confirm that 'most fishing' refers to summed landWt?

Many thanks,
Jess

**Comment by HenrikK-N** [comment]
The 'most fishing' refers to most 'Days at Sea'. See the 'RDBES documentation of the Data Model.docx' on https://github.com/ices-tools-dev/RDBES, see the pages after the section 'Fields in Commercial Effort (CE) data format'.
Br Henrik

**Comment by jcraigMS** [comment]
Thank you
