### ISSUE TITLE
Vessel selection / Selection method / Number of vessels sampled 

### ISSUE THREAD

**Issue by maciek-mir** [ices-tools-dev/RDBES#71]
The question is about the value to be entered into the column "Number of vessels sampled in this stratum" taking into account the method of selecting vessels for sampling in hierarchy no.1.

Suppose we have a data as shown below
|VSstratumName|VSencryptedVesselCode|VSselectionMethod|VSnumberTotal|VSnumberSampled|
|-|-|-|-|-|
|Stratum 1|Vessel 1|SRSWR|15|3|
|Stratum 1|Vessel 2|SRSWR|15|3|
|Stratum 1|Vessel 3|SRSWR|15|3|
|Stratum 1|Vessel 4|NPAH|15|2|
|Stratum 1|Vessel 5|NPAH|15|2|

In the example there is one stratum having two selection methods. One method is probabilist, another is ad-hoc. What is the correct way of registering the number of vessels sampled? Should this number be calculated for every selection method separately, 3 for SRSWR and  2 for NPAH? Or maybe 5 should be entered in all rows as the total number of vessels sampled regardless of the selection method.

**Comment by HenrikK-N** [comment]
This will be discussed at the WKRDB-EST2.

**Comment by HenrikK-N** [comment]
WKRDB-EST2 suggest to set VSnumberSampled = 5, in such situation.

**Comment by nmprista** [comment]
Analysis done at WKRDB-EST2 indicates issue should be re-opened

[WKRDBEST2_Annex5_Issue2_NumberSampled.docx](https://github.com/ices-tools-dev/RDBES/files/6047549/WKRDBEST2_Annex5_Issue2_NumberSampled.docx)

**Comment by lizclarke** [comment]
Discussion at estimation subgroup 28/06/2021

For the 2021 data call, numberSampled should exclude non-responses. In the situation where more than one selection method is used, all samples should be included, so in the example above the numberSampled should be 5.

We propose that Example 1 in the documentation on non-responses (currently page 25) should be flagged as not applicable for the 2021 data call. Example 2 might also need revision. This section is work in progress and will be considered further after the data call. 

This advice raises a difficulty when not all samples should be included in estimation and this will also be considered further.

**Comment by HenrikK-N** [comment]
@lizclarke will look into this for tomorrow at the Core Group meeting.
