### ISSUE TITLE
Table 1 in documentation missing a "(b)" in H9.LE?

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#73]
LE is mandatory but not part of hierarchy according to Annex I. Table 1 may have to be corrected

**Comment by HenrikK-N** [comment]
Yes I will update Table 1 for H9 where it says 'Landing Event' it will be updated to 'Landing Event (c)' and adding a sentence below saying: '(c) LE is not a part of the estimation hierarchy, please see annex for the specific hierarchy 9.'

**Comment by HenrikK-N** [comment]
I have added a (b) to LE for Hiearchy 9 in table 1, I could use the existing (b), so I did not need to make a (c).
