### ISSUE TITLE
Update of clustering descriptions

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#75]
The description of clustering in _at least one_ table of the data model (LE) need to be updated to reflect the new codes (https://vocab.ices.dk/). 

Where it reads
Indicator of absence ("No") or presence of one-stage cluster sampling ("1-stage")or two-stage cluster sampling ("2-stage") of units of that sampling level
Could be
Indicator of absence or presence of different types of one-stage or two-stage cluster sampling within the sampling level

**Comment by HenrikK-N** [comment]
The following checks have now been implemented:
•	if Stratification = Y, then error if RS_Clustering code ='1C' or '2C'.
•	if Stratification = N, then error if RS_Clustering code =  ‘S1C’ or S2C' or '1CS' or '2CS'
