### ISSUE TITLE
CE table - pooled landings and unpowered vessels without kW and GT value

### ISSUE THREAD

**Issue by jcraigMS** [ices-tools-dev/RDBES#77]
We have two situations in which we have no vessel kW or GT values:
- for landings that are pooled with no vessel identified (also no tonnage, and length given as either 0 or 1.8m)
- and unpowered vessels, so no engine power (and tonnage is not collected, but length provided)

How best can these be represented in the CE table?
Am I correct to allocate these to the under 8m vessels (for pooled vessels) with no contribution to kWdays or gtdays etc for both situations?

Or is there a better way to include these?

Many thanks,
Jess

**Comment by HenrikK-N** [comment]
The recommendation is:
In the first option:
  Try to estimate the kW and GT and assume the length class under 8 m and insert the data. 
In the second option:
  It is valid to insert 0 in the kW and GT fields, and the correct length class.
Please do not let this affect the other uploads.
