### ISSUE TITLE
Same SS records of every OS record

### ISSUE THREAD

**Issue by Eucrow** [ices-tools-dev/RDBES#78]
Trying to upload our H5 hierarchy the RDBES return the error in the image attached, indicating duplicates in SS records fos every OS record. But, in our case, an OS record have multiple LE and FT records, with its corresponding SS records. And those SS records should be the same. Indeed, we could have only one SS record of every OS if the hierarchy allowed it.

How can we represent it in the file?

Edit: add an example file to reproduce the error.

![image](https://user-images.githubusercontent.com/10269446/93763630-14fda700-fc12-11ea-8cc6-ac6e6a869c11.png)

[2019_TEST_SS_error_H5.txt](https://github.com/ices-tools-dev/RDBES/files/5255167/2019_TEST_SS_error_H5.txt)

**Comment by HenrikK-N** [comment]
To me it looks like a bug in the checking code, because the Species Selection should be under the Landing Event and not the Onshore Event, we will look into it.

**Comment by davidcurrie2001** [comment]
I have the same problem with H5 data I tried to upload today.  I won't log the issue with rdbsupport@ices.dk since ICES are already aware if it.

**Comment by HenrikK-N** [comment]
The bug should have be fixed now.

**Comment by davidcurrie2001** [comment]
@HenrikK-N I was able to successfully submit my H5 data today.
