### ISSUE TITLE
SAunitType portion of individuals from a basket

### ISSUE THREAD

**Issue by ruizfederico** [ices-tools-dev/RDBES#79]
In the SA table I want to report the taking of a **CLUSTER** of individuals from a basket. What is the best code for reporting it? Can a code 'portion' be added to the SAunitType code list?

**Comment by HenrikK-N** [comment]
It is preferred not to add too many codes, and since it does not matter whether you call the selected a 'portion' or 'box', we prefer to keep the codes. It is therefore suggested that you use 'box' or 'basket'.
