### ISSUE TITLE
Uploading VD and SL tables to RDBES fails

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBES#8]
If the file is named vd.csv or SL.csv it gives a filename format error. 

If the name is ending with _H8 I get 500 (i.e internal server error)

**Comment by davidcurrie2001** [comment]
I think the name needs to end with _HVD or _HSL for for the VD and SL files.

**Comment by rix133** [comment]
> I think the name needs to end with _HVD or _HSL for for the VD and SL files.

Yes this does the trick (lowecase is also OK)

**Comment by HenrikK-N** [comment]
The file naming is '_H1' to '_H9' and '_H10' to '_H13', '_HVD', '_HSL', '_HCL' and '_HCE'. All upper case.
