### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by jcraigMS** [ices-tools-dev/RDBES#82]
I have received the following error when trying to upload the CL and CE tables:

Prechecking passed
 Prechecking is finished with no errors

Data format check failed
 Length cannot be less than zero. Parameter name: length

Can you explain this data format error, as it is preventing upload.

Thank you

**Comment by HenrikK-N** [comment]
You have also send this to RDBsupport@ices.dk and we are looking into it. We will return to you through RDBsupport@ices.dk

**Comment by HenrikK-N** [comment]
I believe this was because of the headers, I will close it now.

**Comment by jcraigMS** [comment]
Thank you,

Jess
