### ISSUE TITLE
Clarifications LOCODES

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#87]
The test data call has helped identify some problems with the use of LOCODES in Norwegian data. LOCODES are used in the mandatory fields CElandingLocation and CLlandingLocation and in some of the sample tables. 

The issues in Norwegian data seems in principle to be solvable, but will require quite some effort, depending on the precision that is required for these parameters. I would therefor like to get some clarifications about the intended use of this data, and perhaps suggest that such clarifications are added to the data field description. I'd also suggest that we consider if the mandatory status of these fields are well motivated.

The issues with the Norwegian data are two-fold:
1. Many locations are assigned different LOCODES in different registers. Norwegian coastal authorities maintain one register, The UN maintains one, and the ICES vocabularies contain one that is derived from the European Master Data Register. For this information to be usable, a careful screening is needed. Since these codes are used in many different systems, several institutions would need to be involved in that. This will necessarily take some time.
2. LOCODES are not integrated in most mandatory industry-reports, and particularly not in sales-notes. In order to map landing-sites to appropriate LOCODES we will need to establish a manually curated reference table. We have some experience in doing this in order to fill sample-tables, but in order to fill the CE and CL tables we would need a complete mapping between landing-sites and LOCODES which will add a considerable workload (~700 entries).

A reconsideration of the mandatory status would of course help this situation a lot. Short of that, some clarification on the precision needed can also simplify the task. If for instance it is sufficient to identify regional centers, we can both reduce the size of auxiliary reference tables, and consider codes in each region that are consistently defined between the different LOCODE-lists mentioned above.

**Comment by HenrikK-N** [comment]
The LOCODE fields is an important field and therefore it should stay mandatory. The basis for the LOCODE is the European Master Data Register, and missing location codes can and should be requested as new locations/harbours. Until the new location have been added the nearest LOCODE should be used.
