### ISSUE TITLE
RS_BiologicalMeasurementType - WeightHeadless

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [ices-tools-dev/RDBES#88]
Is WeightHeadless gutted | ungutted?

**Comment by HenrikK-N** [comment]
This will be forward to WGCATCH and WGBIOP.

**Comment by KirstenBirchHaakansson** [comment]
This is connected to SApresentation

**Comment by KirstenBirchHaakansson** [comment]
I think this should be handled by the RDBES test group - ask them to fill in a list with presentations they have in their national databases

**Comment by HenrikK-N** [comment]
Stock assessement groups will use the whole weight/ungutted. A conversion factor for ‘headless weight convertion factor’ as a parameter. (We also have a live weight in the CL and there there is no convertion factor). WGCATCH: Definitions of the weights, define the biological variables. We could not agree at this point. We will continue the discussion at the next meeting

**Comment by HenrikK-N** [comment]
We think about having two kinds of values; the existing value and a measured for all BVtypes (e.g. , (a conversionfactor is not needed then).
We would add an extra field BVvalueMeasured (optional), and then we have the existing BVvalue (mandatory)(which is the used value).
We would add an extra field for BVtypeMeasuered and then we have the existing BVtype to BVtype  (mandatory)(which is the used value). We will continue the discussion at the next meeting.

**Comment by davidcurrie2001** [comment]
Here is a simple example of the BV changes we were discussing today: [BV_20201104.xlsx](https://github.com/ices-tools-dev/RDBES/files/5488779/BV_20201104.xlsx)
I see Option 1 as the best way to resolve this question.

**Comment by KirstenBirchHaakansson** [comment]
Something a bit different 

SApresentation - we mix state (e.g. frozen) with presentation in this code (e.g. headless)

![image](https://user-images.githubusercontent.com/25765818/99528193-38d53300-299e-11eb-8eed-7d33adf3975f.png)

**Comment by KirstenBirchHaakansson** [comment]
A fast and dirty review of Dave's suggestion 
[Copy of BV_20201104.xlsx](https://github.com/ices-tools-dev/RDBES/files/5559843/Copy.of.BV_20201104.xlsx)

**Comment by KirstenBirchHaakansson** [comment]
And we need to think about the FM

**Comment by nmprista** [comment]
@KirstenBirchHaakansson Seems this issue has already been tackled by SG on Biological Variables, and follow-up plenary. Re-open if it was not.
