### ISSUE TITLE
Inconsistency in coding of lengths in BVtype and FMtype

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [ices-tools-dev/RDBES#90]
BVtype | FMtype
-- | --
Age |  
ForkLength | Fork Length (FM)
HeadLength | Head Length (FM)
Maturity |  
Sex |  
SpecimentState |  
Stock |  
TailLength | Tail Length (FM)
TotalLength | Total Length (FM)
WeightGutted |  
WeightHeadless |  
WeightLive |

**Comment by HenrikK-N** [comment]
The spaces in the FMtype (RS_MeasurementType) will be removed to be consistent with the BVtype (RS_BiologicalMeasurementType).

**Comment by HenrikK-N** [comment]
The RS_BiologicalMeasurementType code type have changed to BiologicalMeasurementType.
The FMtype have changed name to FMtypeMeasured and the code type changed from RS_MeasurementType to BiologicalMeasurementType.
The field FMtypeAssessment have been added with the code type BiologicalMeasurementType.
The code type of the field FMaddGrpMeasurementType have changed from RS_AddGrpMeasurementType to the code type BiologicalMeasurementType.
The code type have been changed from RS_MeasurementType (which is not more in use) to BiologicalMeasurementType. So now all the following fields have the code type BiologicalMeasurementType to be fully consistent. The fields are: BVtypeMeas, BVtypeAssess, FMtypeMeasured, FMtypeAssessment and FMaddGrpMeasurementType. This was all done before the 23 Aug. 2021.
