### ISSUE TITLE
Quality & precision for BVvalues

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [ices-tools-dev/RDBES#91]
Don't we need to add quality and precision of the BVvalues e.g. accuracy for lengths

**Comment by HenrikK-N** [comment]
It is intented to include a quality field in one form (see #85 Quality indicators for Biological Variables) preferably the WGBIOP suggested 4 level scale, which is already in use in DATRAS and SMARTdot. This will be forwarded to WGCATCH and RCG Large Pelagic. It is also intedted to include a precision/accuracy field so far using the same code list as RS_AccuracyCode.

**Comment by nmprista** [comment]
This seems already tackled. @KirstenBirchHaakansson, please re-open if not
