### ISSUE TITLE
CEdataSourceForScientificEffort - add VMS as a data source?

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#92]
Present options under "RS_DataSourceOfScientificWE" are 

Combination of census data,Logbook,Other declarative forms,Sales notes,Sampling data. 

add VMS?

**Comment by HenrikK-N** [comment]
If VMS data is use, then it is used together with other data and then it should use the code: Combcd for combination of census/official data.

**Comment by HenrikK-N** [comment]
Open until the change have been implemented.

**Comment by HenrikK-N** [comment]
It has been implemented and will now be closed.
