### ISSUE TITLE
CLsamplingScheme: code list for RS_NationalProgram

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#94]
Presently code list is 1 and 2 with no definition given [see https://vocab.ices.dk/?ref=1615]

**Comment by HenrikK-N** [comment]
The countries should email to RDBsupport@ices.dk and request their codes for their national programs/sampling schemes, then the codes will be created. If there is no national programs/sampling schemes, then do not fill in the optional field.

**Comment by HenrikK-N** [comment]
The RS_NationalProgram will be substituted by the RS_SamplingScheme in the effort data CE.

**Comment by HenrikK-N** [comment]
The RS_NationalProgram will be substituted by the RS_SamplingScheme in the landing data CL as well also requested at the RDBES meeting 9 Dec. The code list RS_NationalProgram will be deleted.

**Comment by HenrikK-N** [comment]
RS_SamplingScheme have substituted RS_NationalProgram for the renamed fields, which now are called: CLsamplingScheme and CEsamplingScheme. This was before the 23th Aug. 2021.
