### ISSUE TITLE
CLcatchCategory: why is "Dis" an accepted code?

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#95]
RS_CatchCategory contains codes "RegDis" and "Dis". 

Why is "Dis"? how is it defined and when should it be provided? 

Remove it?

**Comment by HenrikK-N** [comment]
A check for limiting the catch categories for the landings data CL will be implemented. The following catch categories will not be accepted for CL: Dis and Catch.

**Comment by HenrikK-N** [comment]
The check for limiting the catch categories for the landings data CL to not accept the codes: Dis and Catch have be implemented.
