### ISSUE TITLE
CLcommercialSizeCategoryScale: Unsorted/NotApplicable missing in codelist?

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#96]
I suggest it is added: see https://vocab.ices.dk/?ref=1624

**Comment by HenrikK-N** [comment]
A code ‘Unsorted’ for unsorted will be added. Not applicable/available will not be added.

**Comment by HenrikK-N** [comment]
The code ‘Unsorted’, desc. 'When catch is not sorted in size categories' have be added.
