### ISSUE TITLE
CLcatchCategory: a few descriptions need clarification

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#97]
see: https://vocab.ices.dk/?ref=1610
- mispelling in codelist - "Registerd Discard"
- Improve BMS definition so it is not ambiguous with landings

**Comment by HenrikK-N** [comment]
CG agreed the following:

Code Description
BMS  Below Minimum Size landing
Catch  Catch (when landing and discard is mixed)
Dis  Discard
Lan  Landing
RegDis  Logbook Registered Discard

**Comment by nmprista** [comment]
see together with issue #98

**Comment by HenrikK-N** [comment]
Done
