### ISSUE TITLE
CLfishingTechnique: needs to be part of the key?

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#99]
CLfishingTechnique is vessel based. The idea behind it appears to be to link RDBES to FDI. To be used that way, considering that it is vessel based, I wonder if it does not need to be part of the CL key?
https://vocab.ices.dk/?ref=1612

**Comment by edvinf** [comment]
I think it is very useful to keep this field optional, as not all RDBES users will necessarily answer FDI data-calls. If it is made part of the key, I suppose it needs to be mandatory. In that case I suggest adding an unknown-code or something similar.

**Comment by josefineegekvist** [comment]
The field is optional and a part of the key.
